package com.zilagent.app.util

object QuoteConstants {
    val HOLIDAY_QUOTES = listOf(
        "Zamanın değerini, onu boşa harcamayanlar bilir.",
        "Dinlenmek, bir sonraki adım için güç toplamaktır.",
        "Huzur, zihnin sessizliğindedir.",
        "En büyük başarı, kendini yönetmektir.",
        "Bugün kendine zaman ayır, yarın için parlayacaksın.",
        "Küçük molalar, büyük fikirleri besler.",
        "Zihninizi dinlendirin, ruhunuzu özgür bırakın.",
        "Plan yapın ama akışta kalmayı da unutmayın.",
        "Başarı, azim ve sabrın meyvesidir.",
        "Tatil, beynin en verimli çalışma yakıtıdır.",
        "Bir gün değil, her gün kendin için bir şey yap.",
        "Yolculuk, varış noktasından daha önemlidir.",
        "Bugünün tadını çıkar, yarın zaten gelecek.",
        "Sessizlikte, kalbinin sesini daha iyi duyarsın.",
        "Gerçek özgürlük, kendi zamanına sahip olmaktır.",
        "Her yeni gün, yeni bir başlangıçtır.",
        "Hayallerine giden yol, dinlenmiş bir zihinden geçer.",
        "Kendine iyi bak, senden sadece bir tane var.",
        "Basitlik, en yüksek gelişmişlik düzeyidir.",
        "Sabahın ilk ışığı, umudun habercisidir.",
        "Bilgi güçtür, ancak zaman en büyük hazinedir.",
        "Gülümse, dünya seninle birlikte aydınlansın.",
        "ZilAgent ile zamanın efendisi sensin.",
        "Düzen, özgürlüğün temelidir.",
        "Bugün sadece nefes al ve anın tadını çıkar.",
        "Eğitim, dünyayı değiştirmek için kullanılan en güçlü silahtır.",
        "Zorluklar, karakteri güçlendiren fırsatlardır.",
        "İyi bir plan, başarının yarısıdır.",
        "Bugün yarının dünüdür, o yüzden kıymetini bil.",
        "Bugün ektiğin tohumlar, yarın gölgesinde dinleneceğin ağaçlar olacaktır.",
        "Bilgi bir hazinedir, ancak uygulama onun anahtarıdır.",
        "Öğrenmeyi bıraktığın gün, yaşlanmaya başladığın gündür.",
        "Sabır, başarının tek gizli bileşenidir.",
        "Büyük başarılar, paylaşılan küçük adımların sonucudur.",
        "Zihin bir paraşüt gibidir; ancak açık olduğunda çalışır.",
        "Okumak, ruhu besleyen en ucuz seyahattir.",
        "Derin düşün, basit konuş, çok sev.",
        "Zamanı öldürmek yerine, onu yaşatmayı öğren.",
        "Her şeyin başında sağlık, her şeyin sonunda huzur vardır.",
        "Hayatın kalitesi, sorularının kalitesiyle ölçülür.",
        "Dibe vurduğunda, gidebileceğin tek yön yukarıdır.",
        "Başarı, hazırlıkla fırsatın karşılaştığı yerdir.",
        "En büyük risk, hiçbir risk almamaktır.",
        "Dünya herkesin zihnindeki kadardır.",
        "Zorluklar, başarının değerini artıran baharatlardır.",
        "Yarınki başarının temeli, bugünkü disiplindir.",
        "Kendine inanmak, zaferin yarısıdır.",
        "Affetmek, ruhun üzerindeki gereksiz yükleri atmaktır.",
        "Bakış açını değiştirirsen, dünyanı değiştirirsin.",
        "Zaman geriye alınamaz, ama gelecek henüz yazılmadı.",
        "İyilik yap, denize at; balık bilmezse HALİK bilir.",
        "Hayatta en hakiki mürşit ilimdir.",
        "Asla vazgeçme; mucizeler her gün olur.",
        "Düşüncelerine dikkat et, eylemlerine dönüşür.",
        "Eylemlerine dikkat et, alışkanlıklarına dönüşür.",
        "Alışkanlıklarına dikkat et, karakterine dönüşür.",
        "Karakterine dikkat et, kaderine dönüşür.",
        "Sessizlik, en güçlü cevaptır bazen.",
        "Bilmediğini bilmek, bilgeliğin başlangıcıdır.",
        "Cesaret, korkusuzluk değil, korkuya rağmen ilerlemektir.",
        "Azla yetinmeyen, çoğu hiç bulamaz.",
        "Mutluluk bir varış noktası değil, bir yolculuk halidir.",
        "Başkalarını tanımak zekadır, kendini tanımak bilgeliktir.",
        "Başka bir yol denemekten korkma.",
        "Hayat, tercihlerin toplamıdır.",
        "En uzun yolculuklar, tek bir adımlarla başlar.",
        "Güneş her gün yeniden doğar, senin gibi.",
        "Umut, hiç bitmeyen bir şarkıdır.",
        "Sevgi, her kapıyı açan tek anahtardır.",
        "Dürüstlük, en pahalı mülktür; ucuz insanlarda bulunmaz.",
        "Zaman, en adil dağıtılmış kaynaktır; herkesin günü 24 saattir.",
        "Önemli olan ne kadar yaşadığın değil, nasıl yaşadığındır.",
        "Güzellik, keşfedilmeyi bekleyen bir detaydır.",
        "Kitaplar, zihne açılan en geniş pencerelerdir.",
        "Ulaşamadığın her şey, senin için bir derstir.",
        "Kendini geliştir, dünya seni takip edecektir.",
        "Asalet, doğuştan değil, davranışla kazanılır.",
        "Bilge olanlar, az konuşur çok dinler.",
        "Hayat kısa, kuşlar uçuyor; zamanın kıymetini bil.",
        "Bir mum, diğer mumu yakmakla ışığından bir şey kaybetmez.",
        "Cahillik, karanlıkların en koyusudur.",
        "Fikirler ölmez, sadece şekil değiştirir.",
        "Hayal kurmak, geleceği tasarlamaktır.",
        "İstikrar, yeteneği yener.",
        "Konuşmadan önce düşün, kırdığın kalbi onarmak zordur.",
        "Merhamet, insanlığın en büyük ziynetidir.",
        "Nasibinde varsa gelir Hint'ten Yemen'den.",
        "Önce sen değiş, sonra dünya değişsin.",
        "Paylaştığın senindir, biriktirdiğin değil.",
        "Rüzgarın yönünü değiştiremiyorsan, yelkenlerini ona göre ayarla.",
        "Söz gümüşse, sükut altındır.",
        "Teşekkür etmek, ruhu genişletir.",
        "Uslan artık deli gönül, zaman akıp gidiyor.",
        "Vefa, sadece bir semt adı değildir.",
        "Yalnızlık, bazen en iyi arkadaştır.",
        "Zahmetsiz rahmet olmaz.",
        "Adalet, mülkün temelidir.",
        "Barış, her şeyin temelidir.",
        "Çalışmak, insanı sıkıntıdan ve yoksulluktan kurtarır.",
        "Dağ ne kadar yüce olsa da, bir yolu vardır.",
        "Emek, en büyük değerdir.",
        "Fırsatlar, kapıyı bir kez çalar; uyanık ol.",
        "Güven, tek kullanımlıktır.",
        "Her kışın sonu bahardır.",
        "Işık, karanlığı yok eden tek şeydir.",
        "İlim, Çin'de bile olsa gidip alınız.",
        "Jilet gibi keskin bir zihin, ancak öğrenmeyle bilenir.",
        "Kader, gayrete aşıktır.",
        "Liderlik, hizmet etmektir.",
        "Mücadele etmeden kazanılan zafer, gerçek değildir.",
        "Nezaket, her kapıyı açan sihirli bir değnektir.",
        "Ortak akıl, en doğru yoldur.",
        "Özgürlük, sorumluluk gerektirir.",
        "Planlı çalışmak, başarının anahtarıdır.",
        "Risk almayan, kazanamaz.",
        "Samimiyet, dilin değil kalbin konuşmasıdır.",
        "Tutumun, irtifanı belirler.",
        "Umut, fakirin ekmeğidir; ama çalışmak zenginin hazinesidir.",
        "Vakit, nakittir.",
        "Yol açık, yola çık.",
        "Zaman, yaraları iyileştirir ama izleri kalabilir.",
        "Akıl akıldan üstündür.",
        "Başarı, ayrıntılarda gizlidir.",
        "Cömertlik, ruhun zenginliğidir.",
        "Değişim, içeriden başlar.",
        "Emanete hıyanet edilmez.",
        "Fikirler, çarpıştıkça parlar.",
        "Gelişim, konfor alanının bittiği yerde başlar.",
        "Hayat, bazen bir saniyeye sığar.",
        "Ilımlılık, her şeyin ölçüsüdür.",
        "İrade, her zorluğu yener.",
        "Kalp kırma, Kabe yıkmaktan beterdir.",
        "Liyakat, hak edilen koltuktur.",
        "Mantık, seni A noktasından B noktasına götürür.",
        "Niyetin neyse, akıbetin odur.",
        "Olan her şeyde bir hayır vardır.",
        "Ölçülü olmak, dengedir.",
        "Pratik yapmak, mükemmelleştirir.",
        "Ruh dinlenmedikçe, beden şifa bulmaz.",
        "Sadelik, şıklığın zirvesidir.",
        "Şüphe, bilginin başlangıcıdır.",
        "Tecrübe, en pahalı okuldur.",
        "Uyanıklık, her zaman tetikte olmaktır.",
        "Üretmek, var olmanın en güzel yoludur.",
        "Vizyon, başkalarının görmediğini görmektir.",
        "Yaratıcılık, zekanın eğlenmesidir.",
        "Zarafet, ruhun inceliğidir.",
        "Ayrılık da sevdaya dahildir.",
        "Birlik olan yerde, dirlik olur.",
        "Coşku, ruhun yakıtıdır.",
        "Dostluk, iki bedende bir ruhtur.",
        "Ego, büyük bir hapishanedir.",
        "Farkındalık, uyanıştır.",
        "Gözlem yapmak, sessizce öğrenmektir.",
        "Hoşgörü, medeniyetin temelidir.",
        "Inanmak, yapmanın yarısıdır.",
        "Iç sesini dinle, o seni yanıltmaz.",
        "Korku, hayallerin katilidir.",
        "Küçük bir iyilik, dünyayı kurtarabilir.",
        "Mucizelere yer aç, onlar her yerdedir.",
        "Nadi bir çiçek gibi, kendini koru.",
        "Okumak, bin kapıyı açmak gibidir.",
        "Paylaşmak, çoğalmaktır.",
        "Ruhunuzu sanatla besleyin.",
        "Soru sormak, cevap bulmanın ilk adımıdır.",
        "Tebessüm, sadakadır.",
        "Ufkunuzu genişletin.",
        "Varlık, paylaştıkça anlam kazanır.",
        "Yolcu, yolundadır.",
        "Zihin, kontrol edilmezse efendi olur.",
        "Adım at, gerisi gelir.",
        "Bakmak başka, görmek başkadır.",
        "Çaba sarf et, meyvesini toplarsın.",
        "Derinlik, yüzeyde bulunmaz.",
        "En büyük savaş, insanın kendiyle olanıdır.",
        "Fırtınalar, ağaçların köklerini güçlendirir.",
        "Gerçek, her zaman açığa çıkar.",
        "Huzur, içsel bir seçimdir.",
        "Israr, başarıyı getirir.",
        "İlham, her an gelebilir.",
        "Karakter, kimse bakmadığında yaptıklarındır.",
        "Lütfetmek, büyüklüktür.",
        "Mükemmeliyetçilik, gelişimin engelidir.",
        "Nasip, çaba ile şekillenir.",
        "Olumluluk, bir yaşam tarzıdır.",
        "Özür dilemek, bir erdemdir.",
        "Pırlanta gibi parlamak için yontulmak gerekir.",
        "Rüya gör, sonra onları gerçekleştir.",
        "Sezgi, mantıktan daha hızlıdır.",
        "Şefkat, yaraları sarar.",
        "Toprak, ne verirsen onu geri verir.",
        "Umursama, sadece ilerle.",
        "Vicdan, insanın içindeki tanrısal sestir.",
        "Yetenek, çalışarak parlar.",
        "Zeki ol, ama kurnaz olma.",
        "Anlamak, affetmektir.",
        "Bağışlamak, seni özgürleştirir.",
        "Cevaplar, sessizlikte saklıdır.",
        "Dünya bir aynadır, ne verirsen onu görürsün.",
        "Engebeli yollar, güzel manzaralara çıkar.",
        "Fedakarlık, sevginin ölçüsüdür.",
        "Geçmiş bir anıdır, gelecek bir gizemdir.",
        "Hayret etmek, öğrenmenin motorudur.",
        "Isığı içinde taşı, gittiğin her yere götür.",
        "İyilik, bulaşıcıdır.",
        "Kendi hikayeni yaz.",
        "Lüks, ihtiyacın olmayana sahip olmaktır.",
        "Mütevazı ol, gerçek büyüklük oradadır.",
        "Nezaket, gücün sessiz dilidir.",
        "Öğrendiğini öğret.",
        "Para, iyi bir uşak ama kötü bir efendidir.",
        "Ruhun, senin gerçek sığınağındır.",
        "Sınırlarını zorla.",
        "Şans, hazırlıklı olanın yanındadır.",
        "Tarih, sadece cesurları hatırlar.",
        "Uzaklar, bir adım ötede başlar.",
        "Vefasızlık, kalbi çürütür.",
        "Yarına kalma, yanına kal.",
        "Zen gibi sakin, fırtına gibi güçlü ol.",
        "Aklın yolu birdir.",
        "Hayatın bir anlamı yoksa, sen ona bir anlam ver.",
        "Bilgi sizi özgür kılar.",
        "ZilAgent ile zaman her daim senin kontrolünde."
    )

    fun getRandomQuote(): String {
        return HOLIDAY_QUOTES.random()
    }

    suspend fun getRandomQuoteFromDb(quoteDao: com.zilagent.app.data.dao.QuoteDao): String {
        val quotes = quoteDao.getAllQuotesSync()
        return if (quotes.isNotEmpty()) {
            quotes.random().content
        } else {
            HOLIDAY_QUOTES.random()
        }
    }
}
