package com.zilagent.app.util

internal data class SystemQuoteSeed(
    val contentTr: String,
    val contentEn: String,
    val source: String,
    val referenceUrl: String,
)

internal val SYSTEM_QUOTE_CATALOG: List<SystemQuoteSeed> = listOf(
    SystemQuoteSeed(
        contentTr = "\u0130nsanlar da\u011flara de\u011fil, k\u00f6stebek tepelerine tak\u0131l\u0131r.",
        contentEn = "Men do not stumble over mountains, but over molehills.",
        source = "Confucius",
        referenceUrl = "https://en.wikiquote.org/wiki/Confucius",
    ),
    SystemQuoteSeed(
        contentTr = "\u0130nsan\u0131n bilgece davranmas\u0131n\u0131n \u00fc\u00e7 yolu vard\u0131r. Birincisi d\u00fc\u015f\u00fcnmedir; en soylusu odur. \u0130kincisi taklittir; en kolay\u0131 odur. \u00dc\u00e7\u00fcnc\u00fcs\u00fc deneyimdir; en ac\u0131s\u0131 odur.",
        contentEn = "Man has three ways of acting wisely. First, by meditation; that is the noblest. Second, by imitation; that is the easiest. Third, by experience; that is the bitterest.",
        source = "Confucius",
        referenceUrl = "https://en.wikiquote.org/wiki/Confucius",
    ),
    SystemQuoteSeed(
        contentTr = "\u0130nsan\u0131 b\u00fcy\u00fck yapan hakikat de\u011fil, hakikati b\u00fcy\u00fck yapan insand\u0131r.",
        contentEn = "It is not truth that makes man great, but man that makes truth great.",
        source = "Confucius",
        referenceUrl = "https://en.wikiquote.org/wiki/Confucius",
    ),
    SystemQuoteSeed(
        contentTr = "Dostlar\u0131m\u0131za g\u00fcvenmemek, onlar taraf\u0131ndan aldat\u0131lmaktan daha utan\u00e7 vericidir.",
        contentEn = "It is more shameful to distrust our friends than to be deceived by them.",
        source = "Confucius",
        referenceUrl = "https://en.wikiquote.org/wiki/Confucius",
    ),
    SystemQuoteSeed(
        contentTr = "\u0130nsan iyi d\u00fc\u015f\u00fcnceler \u00fczerine ne kadar \u00e7ok kafa yorarsa, kendi d\u00fcnyas\u0131 da d\u00fcnyan\u0131n b\u00fct\u00fcn\u00fc de o kadar iyi olur.",
        contentEn = "The more man meditates upon good thoughts, the better will be his world and the world at large.",
        source = "Confucius",
        referenceUrl = "https://en.wikiquote.org/wiki/Confucius",
    ),
    SystemQuoteSeed(
        contentTr = "S\u00fcslenmi\u015f s\u00f6zler ve yapmac\u0131k bir g\u00f6r\u00fcn\u00fc\u015f, ger\u00e7ek erdemle nadiren yan yana bulunur.",
        contentEn = "Fine words and an insinuating appearance are seldom associated with true virtue.",
        source = "Confucius",
        referenceUrl = "https://en.wikiquote.org/wiki/Confucius",
    ),
    SystemQuoteSeed(
        contentTr = "Sad\u0131k ve g\u00fcvenilir olun. Bu bak\u0131mdan sizden a\u015fa\u011f\u0131da olanlarla dostluk kurmay\u0131n. Bir hata yapt\u0131\u011f\u0131n\u0131zda onu d\u00fczeltmekten korkmay\u0131n.",
        contentEn = "Be loyal and trustworthy. Do not befriend anyone who is lower than yourself in this regard. When making a mistake, do not be afraid to correct it.",
        source = "Confucius",
        referenceUrl = "https://en.wikiquote.org/wiki/Confucius",
    ),
    SystemQuoteSeed(
        contentTr = "\u00d6\u011frendiklerini g\u00f6zden ge\u00e7irip yeniden \u00f6\u011frenen ki\u015fi, \u00f6\u011fretmen olmaya uygundur.",
        contentEn = "Reviewing what you have learned and learning anew, you are fit to be a teacher.",
        source = "Confucius",
        referenceUrl = "https://en.wikiquote.org/wiki/Confucius",
    ),
    SystemQuoteSeed(
        contentTr = "\u00dcst\u00fcn insan ku\u015fat\u0131c\u0131d\u0131r, tarafgir de\u011fildir; a\u015fa\u011f\u0131 insan ise tarafgirdir, ku\u015fat\u0131c\u0131 de\u011fildir.",
        contentEn = "The Superior Man is all-embracing and not partial. The inferior man is partial and not all-embracing.",
        source = "Confucius",
        referenceUrl = "https://en.wikiquote.org/wiki/Confucius",
    ),
    SystemQuoteSeed(
        contentTr = "Tao k\u00f6r\u00fck gibidir: bo\u015ftur ama sonsuzca i\u015fler. Onu ne kadar kullan\u0131rsan o kadar \u00fcretir; onun hakk\u0131nda ne kadar \u00e7ok konu\u015fursan o kadar az anlars\u0131n.",
        contentEn = "The Tao is like a bellows: it is empty yet infinitely capable. The more you use it, the more it produces; the more you talk of it, the less you understand.",
        source = "Laozi",
        referenceUrl = "https://en.wikiquote.org/wiki/Laozi",
    ),
    SystemQuoteSeed(
        contentTr = "Tao B\u00fcy\u00fck Ana diye an\u0131l\u0131r: bo\u015ftur ama t\u00fckenmez; sonsuz d\u00fcnyalar\u0131 do\u011furur.",
        contentEn = "The Tao is called the Great Mother: empty yet inexhaustible, it gives birth to infinite worlds.",
        source = "Laozi",
        referenceUrl = "https://en.wikiquote.org/wiki/Laozi",
    ),
    SystemQuoteSeed(
        contentTr = "Zaman ve mek\u00e2ndan \u00f6nce de Tao vard\u0131. Varl\u0131\u011f\u0131n ve yoklu\u011fun \u00f6tesindedir. Bunun do\u011fru oldu\u011funu nereden biliyorum? \u0130\u00e7ime bak\u0131yor ve g\u00f6r\u00fcyorum.",
        contentEn = "Since before time and space were, the Tao is. It is beyond being and non-being. How do I know this is true? I look inside myself and see.",
        source = "Laozi",
        referenceUrl = "https://en.wikiquote.org/wiki/Laozi",
    ),
    SystemQuoteSeed(
        contentTr = "Ba\u015fkalar\u0131n\u0131 bilmek zek\u00e2d\u0131r; kendini bilmek ger\u00e7ek bilgeliktir. Ba\u015fkalar\u0131na h\u00fckmetmek g\u00fc\u00e7t\u00fcr; kendine h\u00fckmetmek ger\u00e7ek kudrettir.",
        contentEn = "Knowing others is intelligence; knowing yourself is true wisdom. Mastering others is strength; mastering yourself is true power.",
        source = "Laozi",
        referenceUrl = "https://en.wikiquote.org/wiki/Laozi",
    ),
    SystemQuoteSeed(
        contentTr = "Yeterin ger\u00e7ekten yeter oldu\u011funu bilenin, daima yeteri vard\u0131r.",
        contentEn = "He who knows that enough is enough will always have enough.",
        source = "Laozi",
        referenceUrl = "https://en.wikiquote.org/wiki/Laozi",
    ),
    SystemQuoteSeed(
        contentTr = "B\u0131rakt\u0131\u011f\u0131nda her \u015fey tamam olur. D\u00fcnya, b\u0131rakabilenlerin kazan\u0131m\u0131d\u0131r. Ama sen durmadan zorlad\u0131\u011f\u0131nda, d\u00fcnya kazan\u0131lmaz olur.",
        contentEn = "By letting it go it all gets done. The world is won by those who let it go. But when you try and try, the world is beyond the winning.",
        source = "Laozi",
        referenceUrl = "https://en.wikiquote.org/wiki/Laozi",
    ),
    SystemQuoteSeed(
        contentTr = "Bilgiye ula\u015fmak i\u00e7in her g\u00fcn bir \u015fey ekle. Bilgeli\u011fe ula\u015fmak i\u00e7in her g\u00fcn bir \u015fey \u00e7\u0131kar.",
        contentEn = "To attain knowledge, add things every day. To attain wisdom, remove things every day.",
        source = "Laozi",
        referenceUrl = "https://en.wikiquote.org/wiki/Laozi",
    ),
    SystemQuoteSeed(
        contentTr = "Tanr\u0131lardan gelen her \u015fey inayetle doludur.",
        contentEn = "All that is from the gods is full of Providence.",
        source = "Marcus Aurelius",
        referenceUrl = "https://en.wikiquote.org/wiki/Marcus_Aurelius",
    ),
    SystemQuoteSeed(
        contentTr = "Bir insan\u0131n elinde bulunmas\u0131 gereken \u015feylerin ne kadar az oldu\u011funu g\u00f6r\u00fcrs\u00fcn; bunlara sahipse ya\u015fam\u0131 sakince ve tanr\u0131sal bi\u00e7imde akar.",
        contentEn = "Thou seest how few be the things, the which if a man has at his command his life flows gently on and is divine.",
        source = "Marcus Aurelius",
        referenceUrl = "https://en.wikiquote.org/wiki/Marcus_Aurelius",
    ),
    SystemQuoteSeed(
        contentTr = "Kendine yeni ve iyi bir \u015fey \u00f6\u011frenmek i\u00e7in zaman ver; savrulup durmaktan vazge\u00e7.",
        contentEn = "Give thyself time to learn something new and good, and cease to be whirled around.",
        source = "Marcus Aurelius",
        referenceUrl = "https://en.wikiquote.org/wiki/Marcus_Aurelius",
    ),
    SystemQuoteSeed(
        contentTr = "En uzun ya\u015fayanla en k\u0131sa ya\u015fayan ki\u015fi, \u00f6ld\u00fcklerinde ayn\u0131 \u015feyi kaybeder.",
        contentEn = "The longest-lived and the shortest-lived man, when they come to die, lose one and the same thing.",
        source = "Marcus Aurelius",
        referenceUrl = "https://en.wikiquote.org/wiki/Marcus_Aurelius",
    ),
    SystemQuoteSeed(
        contentTr = "Unutma ki her \u015fey bir yarg\u0131d\u0131r.",
        contentEn = "Remember that all is opinion.",
        source = "Marcus Aurelius",
        referenceUrl = "https://en.wikiquote.org/wiki/Marcus_Aurelius",
    ),
    SystemQuoteSeed(
        contentTr = "Hayata gelince, o bir sava\u015f ve yabanc\u0131 bir diyarda k\u0131sa bir konaklamad\u0131r; geride kalan \u00fcn ise unutulu\u015ftur.",
        contentEn = "As for life, it is a battle and a sojourning in a strange land; but the fame that comes after is oblivion.",
        source = "Marcus Aurelius",
        referenceUrl = "https://en.wikiquote.org/wiki/Marcus_Aurelius",
    ),
    SystemQuoteSeed(
        contentTr = "Kalan \u00f6mr\u00fcn\u00fc, ortak iyili\u011fe katk\u0131 sunmayan ba\u015fkalar\u0131yla ilgili hayallerde t\u00fcketme.",
        contentEn = "Waste not the remnant of thy life in those imaginations touching other folk, whereby thou contributest not to the common weal.",
        source = "Marcus Aurelius",
        referenceUrl = "https://en.wikiquote.org/wiki/Marcus_Aurelius",
    ),
    SystemQuoteSeed(
        contentTr = "Her insana d\u00fc\u015fen pay ona uygundur ve onu da kendi pay\u0131na uygun k\u0131lar.",
        contentEn = "The lot assigned to every man is suited to him, and suits him to itself.",
        source = "Marcus Aurelius",
        referenceUrl = "https://en.wikiquote.org/wiki/Marcus_Aurelius",
    ),
    SystemQuoteSeed(
        contentTr = "Yapt\u0131\u011f\u0131nda isteksiz olma; bencil, d\u00fc\u015f\u00fcncesiz ya da inat\u00e7\u0131 olma; d\u00fc\u015f\u00fcnceni a\u015f\u0131r\u0131 incelikle s\u00fcsleme; geveze ya da her i\u015fe burnunu sokan biri olma.",
        contentEn = "Be not unwilling in what thou doest, neither selfish nor unadvised nor obstinate; let not over-refinement deck out thy thought; be not wordy nor a busybody.",
        source = "Marcus Aurelius",
        referenceUrl = "https://en.wikiquote.org/wiki/Marcus_Aurelius",
    ),
    SystemQuoteSeed(
        contentTr = "Felsefe, hakikatin bilimidir.",
        contentEn = "Philosophy is the science of truth.",
        source = "Aristotle",
        referenceUrl = "https://en.wikiquote.org/wiki/Aristotle",
    ),
    SystemQuoteSeed(
        contentTr = "Do\u011fa hi\u00e7bir \u015feyi bo\u015funa yapmaz.",
        contentEn = "Nature does not do anything in vain.",
        source = "Aristotle",
        referenceUrl = "https://en.wikiquote.org/wiki/Aristotle",
    ),
    SystemQuoteSeed(
        contentTr = "Hakikatten en k\u00fc\u00e7\u00fck ilk sapma, sonras\u0131nda bin kat b\u00fcy\u00fcr.",
        contentEn = "The least initial deviation from the truth is multiplied later a thousandfold.",
        source = "Aristotle",
        referenceUrl = "https://en.wikiquote.org/wiki/Aristotle",
    ),
    SystemQuoteSeed(
        contentTr = "Do\u011fa sonsuz olandan ka\u00e7ar; \u00e7\u00fcnk\u00fc sonsuz olan bitimsiz ya da eksiktir, oysa Do\u011fa hep bir sona y\u00f6nelir.",
        contentEn = "Nature flies from the infinite, for the infinite is unending or imperfect, and Nature ever seeks an end.",
        source = "Aristotle",
        referenceUrl = "https://en.wikiquote.org/wiki/Aristotle",
    ),
    SystemQuoteSeed(
        contentTr = "M\u00fczik ruhun tutkular\u0131n\u0131 do\u011frudan temsil eder. \u0130nsan yanl\u0131\u015f t\u00fcrde bir m\u00fczi\u011fi dinlerse yanl\u0131\u015f t\u00fcrde bir insana d\u00f6n\u00fc\u015f\u00fcr.",
        contentEn = "Music directly represents the passion of the soul. If one listens to the wrong kind of music, he will become the wrong kind of person.",
        source = "Aristotle",
        referenceUrl = "https://en.wikiquote.org/wiki/Aristotle",
    ),
    SystemQuoteSeed(
        contentTr = "Bilge insan emredilen de\u011fil, emreden olmal\u0131d\u0131r; ba\u015fkas\u0131na itaat etmemeli, daha az bilge olan ona itaat etmelidir.",
        contentEn = "The wise man must not be ordered but must order, and he must not obey another, but the less wise must obey him.",
        source = "Aristotle",
        referenceUrl = "https://en.wikiquote.org/wiki/Aristotle",
    ),
    SystemQuoteSeed(
        contentTr = "Kendisi i\u00e7in ve bilmek u\u011fruna arzulanan \u015fey, sonu\u00e7lar\u0131 u\u011fruna arzulanan \u015feyden daha \u00e7ok bilgeli\u011fin do\u011fas\u0131ndad\u0131r.",
        contentEn = "That which is desirable on its own account and for the sake of knowing it is more of the nature of wisdom than that which is desirable on account of its results.",
        source = "Aristotle",
        referenceUrl = "https://en.wikiquote.org/wiki/Aristotle",
    ),
    SystemQuoteSeed(
        contentTr = "B\u00fct\u00fcn, salt bir y\u0131\u011f\u0131n de\u011fildir; b\u00fct\u00fcn, par\u00e7alar\u0131n \u00f6tesinde bir \u015feydir.",
        contentEn = "The totality is not, as it were, a mere heap, but the whole is something besides the parts.",
        source = "Aristotle",
        referenceUrl = "https://en.wikiquote.org/wiki/Aristotle",
    ),
    SystemQuoteSeed(
        contentTr = "\u0130nsanlar, pek de haks\u0131z say\u0131lmaz bi\u00e7imde, en y\u00fcksek iyilik ve mutluluk \u00fczerine d\u00fc\u015f\u00fcncelerini insan ya\u015famlar\u0131ndan \u00e7\u0131kar\u0131rlar.",
        contentEn = "Now men seem, not unreasonably, to form their notions of the supreme good and of happiness from the lives of men.",
        source = "Aristotle",
        referenceUrl = "https://en.wikiquote.org/wiki/Aristotle",
    ),
    SystemQuoteSeed(
        contentTr = "Ak\u0131ll\u0131 varl\u0131k i\u00e7in katlan\u0131lmaz olan yaln\u0131zca ak\u0131ld\u0131\u015f\u0131 oland\u0131r; akla uygun olan ise katlan\u0131labilirdir.",
        contentEn = "To the rational being only the irrational is unendurable, but the rational is endurable.",
        source = "Epictetus",
        referenceUrl = "https://en.wikiquote.org/wiki/Epictetus",
    ),
    SystemQuoteSeed(
        contentTr = "K\u0131sacas\u0131, ne \u00f6l\u00fcm, ne s\u00fcrg\u00fcn, ne ac\u0131 ne de buna benzer herhangi bir \u015fey, bir \u015feyi yapmam\u0131z\u0131n ya da yapmamam\u0131z\u0131n ger\u00e7ek nedeni de\u011fildir; neden, i\u00e7imizdeki yarg\u0131lar ve ilkelerimizdir.",
        contentEn = "In a word, neither death, nor exile, nor pain, nor anything of this kind is the real cause of our doing or not doing any action, but our inward opinions and principles.",
        source = "Epictetus",
        referenceUrl = "https://en.wikiquote.org/wiki/Epictetus",
    ),
    SystemQuoteSeed(
        contentTr = "Ak\u0131l, b\u00fcy\u00fckl\u00fckle ya da boyla de\u011fil, ilkeyle \u00f6l\u00e7\u00fcl\u00fcr.",
        contentEn = "Reason is not measured by size or height, but by principle.",
        source = "Epictetus",
        referenceUrl = "https://en.wikiquote.org/wiki/Epictetus",
    ),
    SystemQuoteSeed(
        contentTr = "Yarat\u0131l\u0131\u015fta tek bir \u015fey bile, al\u00e7akg\u00f6n\u00fcll\u00fc ve \u015f\u00fckreden bir zihne inayeti g\u00f6stermeye yeter.",
        contentEn = "Any one thing in the creation is sufficient to demonstrate a Providence to an humble and grateful mind.",
        source = "Epictetus",
        referenceUrl = "https://en.wikiquote.org/wiki/Epictetus",
    ),
    SystemQuoteSeed(
        contentTr = "\u00d6teki her \u015feyi bi\u00e7imlendiren ve d\u00fczenleyen Ak\u0131l oldu\u011funa g\u00f6re, kendisi d\u00fczensiz b\u0131rak\u0131lmamal\u0131d\u0131r.",
        contentEn = "Since it is Reason which shapes and regulates all other things, it ought not itself to be left in disorder.",
        source = "Epictetus",
        referenceUrl = "https://en.wikiquote.org/wiki/Epictetus",
    ),
    SystemQuoteSeed(
        contentTr = "Tanr\u0131 a\u015fk\u0131na, \u00f6nce k\u00fc\u00e7\u00fck \u015feylerde kendini al\u0131\u015ft\u0131r; sonra daha b\u00fcy\u00fc\u011f\u00fcne ge\u00e7.",
        contentEn = "Practice yourself, for heaven's sake, in little things; and thence proceed to greater.",
        source = "Epictetus",
        referenceUrl = "https://en.wikiquote.org/wiki/Epictetus",
    ),
    SystemQuoteSeed(
        contentTr = "\u0130nsanlar\u0131n ne oldu\u011funu g\u00f6steren \u015fey zorluklard\u0131r.",
        contentEn = "It is difficulties that show what men are.",
        source = "Epictetus",
        referenceUrl = "https://en.wikiquote.org/wiki/Epictetus",
    ),
    SystemQuoteSeed(
        contentTr = "\u0130nsan\u0131n iyi ya da k\u00f6t\u00fc h\u00e2linin kendi iradesinde bulundu\u011funu, di\u011fer her \u015feyin bizim i\u00e7in \u00f6nemsiz oldu\u011funu s\u00f6yl\u00fcyorsak, neden h\u00e2l\u00e2 huzursuzuz?",
        contentEn = "If we are not stupid or insincere when we say that the good or ill of man lies within his own will, and that all beside is nothing to us, why are we still troubled?",
        source = "Epictetus",
        referenceUrl = "https://en.wikiquote.org/wiki/Epictetus",
    ),
    SystemQuoteSeed(
        contentTr = "Oda dumanl\u0131ysa, azsa kal\u0131r\u0131m; \u00e7oksa \u00e7\u0131kar\u0131m. Bunu unutma, buna s\u0131k\u0131ca tutun: kap\u0131 daima a\u00e7\u0131kt\u0131r.",
        contentEn = "If the room is smoky, if only moderately, I will stay; if there is too much smoke I will go. Remember this, keep a firm hold on it, the door is always open.",
        source = "Epictetus",
        referenceUrl = "https://en.wikiquote.org/wiki/Epictetus",
    ),
    SystemQuoteSeed(
        contentTr = "Bir insana \u00f6fkelenmek ondan nefret etmektir; ondan nefret etmek ona zarar istemektir; sana zarar vermi\u015f olsa bile ona iyilik dilemek ise b\u00fcy\u00fck ruhun i\u015faretidir.",
        contentEn = "To be angry with a man is to hate him; to hate him is to wish him harm; but to wish him well, even if he has done you harm, is the mark of a great mind.",
        source = "Seneca the Younger",
        referenceUrl = "https://en.wikiquote.org/wiki/Seneca_the_Younger",
    ),
    SystemQuoteSeed(
        contentTr = "Yeniden, ba\u015far\u0131l\u0131 ve talihli su\u00e7 erdem diye adland\u0131r\u0131l\u0131r; iyiler k\u00f6t\u00fclere boyun e\u011fer, g\u00fc\u00e7 hak say\u0131l\u0131r, korku hukuku ezer.",
        contentEn = "Once again prosperous and successful crime goes by the name of virtue; good men obey the bad, might is right and fear oppresses law.",
        source = "Seneca the Younger",
        referenceUrl = "https://en.wikiquote.org/wiki/Seneca_the_Younger",
    ),
    SystemQuoteSeed(
        contentTr = "Adaletsiz talih, en y\u00fcksek de\u011feri nadiren esirger; b\u00f6ylesine s\u0131k tehlikelerin kar\u015f\u0131s\u0131nda hi\u00e7 kimse uzun s\u00fcre g\u00fcven i\u00e7inde duramaz. Felaket s\u0131k s\u0131k yan\u0131ndan ge\u00e7se de sonunda onu bulur.",
        contentEn = "Unrighteous fortune seldom spares the highest worth; no one with safety can long front so frequent perils. Whom calamity oft passes by she finds at last.",
        source = "Seneca the Younger",
        referenceUrl = "https://en.wikiquote.org/wiki/Seneca_the_Younger",
    ),
    SystemQuoteSeed(
        contentTr = "Soyuyla \u00f6v\u00fcnen, ba\u015fkas\u0131na ait olan\u0131 \u00f6ver.",
        contentEn = "Who vaunts his race, lauds what belongs to others.",
        source = "Seneca the Younger",
        referenceUrl = "https://en.wikiquote.org/wiki/Seneca_the_Younger",
    ),
    SystemQuoteSeed(
        contentTr = "Zorlanabilen ki\u015fi, nas\u0131l \u00f6lece\u011fini hen\u00fcz \u00f6\u011frenmemi\u015ftir.",
        contentEn = "Who can be forced has not learned how to die.",
        source = "Seneca the Younger",
        referenceUrl = "https://en.wikiquote.org/wiki/Seneca_the_Younger",
    ),
    SystemQuoteSeed(
        contentTr = "Katlanmas\u0131 g\u00fc\u00e7 olan \u015feyleri sonradan anmak ho\u015f gelir.",
        contentEn = "Things 'twas hard to bear 'tis pleasant to recall.",
        source = "Seneca the Younger",
        referenceUrl = "https://en.wikiquote.org/wiki/Seneca_the_Younger",
    ),
    SystemQuoteSeed(
        contentTr = "Elindeyken g\u00fcnah\u0131 engellemeyen, ona emretmi\u015f olur.",
        contentEn = "He who, when he may, forbids not sin, commands it.",
        source = "Seneca the Younger",
        referenceUrl = "https://en.wikiquote.org/wiki/Seneca_the_Younger",
    ),
    SystemQuoteSeed(
        contentTr = "\u00d6\u011f\u00fct alabilen keder k\u00fc\u00e7\u00fckt\u00fcr.",
        contentEn = "Small the grief is that can counsel take.",
        source = "Seneca the Younger",
        referenceUrl = "https://en.wikiquote.org/wiki/Seneca_the_Younger",
    ),
    SystemQuoteSeed(
        contentTr = "Hi\u00e7bir \u015fey ummayan adam\u0131n en az\u0131ndan korkacak \u015feyi de yoktur.",
        contentEn = "The man who hopes for naught at least has naught to fear.",
        source = "Seneca the Younger",
        referenceUrl = "https://en.wikiquote.org/wiki/Seneca_the_Younger",
    ),
    SystemQuoteSeed(
        contentTr = "Sessizli\u011finizin onay anlam\u0131na geldi\u011fini varsayaca\u011f\u0131m.",
        contentEn = "I shall assume that your silence gives consent.",
        source = "Plato",
        referenceUrl = "https://en.wikiquote.org/wiki/Plato",
    ),
    SystemQuoteSeed(
        contentTr = "Hayret, filozofun duygusudur; felsefe hayretle ba\u015flar.",
        contentEn = "Wonder is the feeling of a philosopher, and philosophy begins in wonder.",
        source = "Plato",
        referenceUrl = "https://en.wikiquote.org/wiki/Plato",
    ),
    SystemQuoteSeed(
        contentTr = "Alg\u0131 ile bilgi asla ayn\u0131 \u015fey olamazd\u0131.",
        contentEn = "Perception and knowledge could never be the same.",
        source = "Plato",
        referenceUrl = "https://en.wikiquote.org/wiki/Plato",
    ),
    SystemQuoteSeed(
        contentTr = "\u0130lerleyi\u015fi yava\u015f da olsa s\u00fcrekli olan hi\u00e7 kimse cesaretini yitirmemelidir, Theaetetus.",
        contentEn = "No one should be discouraged, Theaetetus, who can make constant progress, even though it be slow.",
        source = "Plato",
        referenceUrl = "https://en.wikiquote.org/wiki/Plato",
    ),
    SystemQuoteSeed(
        contentTr = "Parmenides: Bir olmadan \u00e7oklu\u011fu d\u00fc\u015f\u00fcnmek imk\u00e2ns\u0131zd\u0131r.",
        contentEn = "Parmenides: It is impossible to conceive of many without one.",
        source = "Plato",
        referenceUrl = "https://en.wikiquote.org/wiki/Plato",
    ),
    SystemQuoteSeed(
        contentTr = "Parmenides: T\u0131pk\u0131 bir resimdeki \u015feylerin uzaktan bak\u0131ld\u0131\u011f\u0131nda tek ve ayn\u0131 durumda, birbirine benzer g\u00f6r\u00fcnmesi gibi.",
        contentEn = "Parmenides: Just as things in a picture, when viewed from a distance, appear to be all in one and the same condition and alike.",
        source = "Plato",
        referenceUrl = "https://en.wikiquote.org/wiki/Plato",
    ),
    SystemQuoteSeed(
        contentTr = "Benim i\u00e7in en iyisi, kalabal\u0131klar\u0131n benimle anla\u015fmamas\u0131ndansa, tek bir ki\u015fi olarak benim kendimle uyumsuz olmamamd\u0131r.",
        contentEn = "It would be better for me ... that multitudes of men should disagree with me rather than that I, being one, should be out of harmony with myself.",
        source = "Plato",
        referenceUrl = "https://en.wikiquote.org/wiki/Plato",
    ),
    SystemQuoteSeed(
        contentTr = "Neyin tehlike olup olmad\u0131\u011f\u0131n\u0131 bilen bilgelik, bunlar\u0131 bilmeyen cehaletin kar\u015f\u0131t\u0131d\u0131r.",
        contentEn = "The wisdom which knows what are and are not dangers is opposed to the ignorance of them.",
        source = "Plato",
        referenceUrl = "https://en.wikiquote.org/wiki/Plato",
    ),
    SystemQuoteSeed(
        contentTr = "Hepimizin s\u00f6yledi\u011fi her \u015fey, ancak bir taklit ve temsil olabilir.",
        contentEn = "All that is said by any of us can only be imitation and representation.",
        source = "Plato",
        referenceUrl = "https://en.wikiquote.org/wiki/Plato",
    ),
    SystemQuoteSeed(
        contentTr = "Yi\u011fitlik, talihsiz olsa bile d\u00fc\u015fmanlardan b\u00fcy\u00fck sayg\u0131 g\u00f6r\u00fcr; ama Romal\u0131lar, ba\u015far\u0131l\u0131 bile olsa korkakl\u0131\u011f\u0131 k\u00fc\u00e7\u00fcmser.",
        contentEn = "Valour, however unfortunate, commands great respect even from enemies: but the Romans despise cowardice, even though it be prosperous.",
        source = "Plutarch",
        referenceUrl = "https://en.wikiquote.org/wiki/Plutarch",
    ),
    SystemQuoteSeed(
        contentTr = "Sebat, zorbal\u0131ktan daha etkilidir; birlikteyken yenilemeyen bir\u00e7ok \u015fey, teker teker ele al\u0131nd\u0131\u011f\u0131nda boyun e\u011fer.",
        contentEn = "Perseverance is more prevailing than violence; and many things which cannot be overcome when they are together, yield themselves up when taken little by little.",
        source = "Plutarch",
        referenceUrl = "https://en.wikiquote.org/wiki/Plutarch",
    ),
    SystemQuoteSeed(
        contentTr = "Yetki ve makam, insanlar\u0131n mizac\u0131n\u0131 s\u0131nar; her tutkuyu harekete ge\u00e7irerek her zay\u0131fl\u0131\u011f\u0131 a\u00e7\u0131\u011fa \u00e7\u0131kar\u0131r.",
        contentEn = "Authority and place demonstrate and try the tempers of men, by moving every passion and discovering every frailty.",
        source = "Plutarch",
        referenceUrl = "https://en.wikiquote.org/wiki/Plutarch",
    ),
    SystemQuoteSeed(
        contentTr = "Zaman\u0131n buyru\u011funa uy; \u00e7\u00fcnk\u00fc o, b\u00fct\u00fcn dan\u0131\u015fmanlar\u0131n en bilgesidir.",
        contentEn = "Be ruled by time, the wisest counsellor of all.",
        source = "Plutarch",
        referenceUrl = "https://en.wikiquote.org/wiki/Plutarch",
    ),
    SystemQuoteSeed(
        contentTr = "B\u00fcy\u00fck tanr\u0131 Pan \u00f6ld\u00fc.",
        contentEn = "The great god Pan is dead.",
        source = "Plutarch",
        referenceUrl = "https://en.wikiquote.org/wiki/Plutarch",
    ),
    SystemQuoteSeed(
        contentTr = "Eldeki ku\u015fu, daldaki ku\u015f i\u00e7in ka\u00e7\u0131ran ahmakt\u0131r.",
        contentEn = "He is a fool who lets slip a bird in the hand for a bird in the bush.",
        source = "Plutarch",
        referenceUrl = "https://en.wikiquote.org/wiki/Plutarch",
    ),
    SystemQuoteSeed(
        contentTr = "Zihin doldurulmas\u0131 gereken bir kap de\u011fil, tutu\u015fturulmas\u0131 gereken bir odundur.",
        contentEn = "The mind is not a vessel that needs filling, but wood that needs igniting.",
        source = "Plutarch",
        referenceUrl = "https://en.wikiquote.org/wiki/Plutarch",
    ),
    SystemQuoteSeed(
        contentTr = "Ya\u015fl\u0131 Dionysios'a bo\u015f vakti olup olmad\u0131\u011f\u0131 soruldu\u011funda, 'Tanr\u0131 korusun, ba\u015f\u0131ma b\u00f6yle bir \u015fey gelmesin!' diye cevap verdi.",
        contentEn = "Dionysius the Elder, being asked whether he was at leisure, replied: \"God forbid that it should ever befall me!\"",
        source = "Plutarch",
        referenceUrl = "https://en.wikiquote.org/wiki/Plutarch",
    ),
    SystemQuoteSeed(
        contentTr = "Geveze bir berber, Arkhelaos'a sa\u00e7\u0131n\u0131 nas\u0131l kestirmek istedi\u011fini sordu. O da, 'Sessizlik i\u00e7inde,' dedi.",
        contentEn = "A prating barber asked Archelaus how he would be trimmed. He answered: \"In silence.\"",
        source = "Plutarch",
        referenceUrl = "https://en.wikiquote.org/wiki/Plutarch",
    ),
    SystemQuoteSeed(
        contentTr = "Sab\u0131rl\u0131 ol! Her \u015fey kolayla\u015fmadan \u00f6nce zordur.",
        contentEn = "Have patience! All things are difficult before they become easy.",
        source = "Saadi",
        referenceUrl = "https://en.wikiquote.org/wiki/Saadi",
    ),
    SystemQuoteSeed(
        contentTr = "Midesine k\u00f6le olan ki\u015fi Tanr\u0131'ya pek ibadet etmez.",
        contentEn = "He who is a slave to his stomach seldom worships God.",
        source = "Saadi",
        referenceUrl = "https://en.wikiquote.org/wiki/Saadi",
    ),
    SystemQuoteSeed(
        contentTr = "Kar\u0131n bo\u015fken beden ruha d\u00f6n\u00fc\u015f\u00fcr; doluyken ruh bedene d\u00f6n\u00fc\u015f\u00fcr.",
        contentEn = "When the belly is empty, the body becomes spirit; when it is full, the spirit becomes body.",
        source = "Saadi",
        referenceUrl = "https://en.wikiquote.org/wiki/Saadi",
    ),
    SystemQuoteSeed(
        contentTr = "Ruh okumay\u0131 \u00f6\u011frendi\u011finde, a\u011fac\u0131n her yapra\u011f\u0131 kutsal kitab\u0131n bir sayfas\u0131na d\u00f6n\u00fc\u015f\u00fcr.",
        contentEn = "Every leaf of the tree becomes a page of the sacred scripture once the soul has learnt to read.",
        source = "Saadi",
        referenceUrl = "https://en.wikiquote.org/wiki/Saadi",
    ),
    SystemQuoteSeed(
        contentTr = "Sevgilisini kollar\u0131nda tutanla, g\u00f6zlerini kap\u0131ya dikmi\u015f onu bekleyen aras\u0131nda fark vard\u0131r.",
        contentEn = "There is a difference between him who claspeth his mistress in his arms, and him whose eyes are fixed on the door expecting her.",
        source = "Saadi",
        referenceUrl = "https://en.wikiquote.org/wiki/Saadi",
    ),
    SystemQuoteSeed(
        contentTr = "Zenginlik istiyorsan, istemen gereken yaln\u0131zca kanaattir; \u00e7\u00fcnk\u00fc o b\u00fcy\u00fck bir hazinedir.",
        contentEn = "If thou covetest riches, ask not but for contentment, which is an immense treasure.",
        source = "Saadi",
        referenceUrl = "https://en.wikiquote.org/wiki/Saadi",
    ),
    SystemQuoteSeed(
        contentTr = "Tatl\u0131 bir dil, nezaket ve yumu\u015fakl\u0131k kullan; b\u00f6ylece bir fili bile bir k\u0131lla y\u00f6nlendirebilirsin.",
        contentEn = "Use a sweet tongue, courtesy, and gentleness, and thou mayst manage to guide an elephant with a hair.",
        source = "Saadi",
        referenceUrl = "https://en.wikiquote.org/wiki/Saadi",
    ),
    SystemQuoteSeed(
        contentTr = "Dalg\u0131\u00e7 k\u00f6pekbal\u0131\u011f\u0131n\u0131n \u00e7enesini d\u00fc\u015f\u00fcnseydi, de\u011ferli incinin pe\u015fine asla d\u00fc\u015fmezdi.",
        contentEn = "Were the diver to think on the jaws of the shark, he would never lay hands on the precious pearl.",
        source = "Saadi",
        referenceUrl = "https://en.wikiquote.org/wiki/Saadi",
    ),
    SystemQuoteSeed(
        contentTr = "Kalpte iz b\u0131rakan her \u015fey, g\u00f6ze de g\u00fczel g\u00f6r\u00fcn\u00fcr.",
        contentEn = "Whatever makes an impression on the heart seems lovely in the eye.",
        source = "Saadi",
        referenceUrl = "https://en.wikiquote.org/wiki/Saadi",
    ),
    SystemQuoteSeed(
        contentTr = "Akl\u0131 arzusunu yenen ki\u015fi meleklerden y\u00fccedir; arzusu akl\u0131n\u0131 yenen ki\u015fi ise hayvandan a\u015fa\u011f\u0131d\u0131r.",
        contentEn = "He whose intellect overcomes his desire is higher than the angels; he whose desire overcomes his intellect is less than an animal.",
        source = "Rumi",
        referenceUrl = "https://en.wikiquote.org/wiki/Rumi",
    ),
    SystemQuoteSeed(
        contentTr = "Su\u00e7layan ki\u015fide kusur vard\u0131r. Ruh, ele\u015ftirecek bir \u015fey g\u00f6rmez.",
        contentEn = "The fault is in the one who blames. Spirit sees nothing to criticize.",
        source = "Rumi",
        referenceUrl = "https://en.wikiquote.org/wiki/Rumi",
    ),
    SystemQuoteSeed(
        contentTr = "K\u0131skan\u00e7l\u0131\u011f\u0131 yol arkada\u015f\u0131 etmeyen ki\u015fi ne mutludur.",
        contentEn = "Fortunate is he who does not carry envy as a companion.",
        source = "Rumi",
        referenceUrl = "https://en.wikiquote.org/wiki/Rumi",
    ),
    SystemQuoteSeed(
        contentTr = "Benli\u011finin putu, b\u00fct\u00fcn putlar\u0131n anas\u0131d\u0131r. Benli\u011fi kolayca boyun e\u011fdirilecek sanmak hatad\u0131r.",
        contentEn = "The idol of your self is the mother of all idols. To regard the self as easy to subdue is a mistake.",
        source = "Rumi",
        referenceUrl = "https://en.wikiquote.org/wiki/Rumi",
    ),
    SystemQuoteSeed(
        contentTr = "Merhamet istiyorsan, g\u00fc\u00e7s\u00fcze merhamet g\u00f6ster.",
        contentEn = "If you wish mercy, show mercy to the weak.",
        source = "Rumi",
        referenceUrl = "https://en.wikiquote.org/wiki/Rumi",
    ),
    SystemQuoteSeed(
        contentTr = "Ba\u015fkalar\u0131n\u0131n d\u00fc\u015fmesi i\u00e7in kuyu kazarsan, i\u00e7ine kendin d\u00fc\u015fersin.",
        contentEn = "If you dig a pit for others to fall into, you will fall into it yourself.",
        source = "Rumi",
        referenceUrl = "https://en.wikiquote.org/wiki/Rumi",
    ),
    SystemQuoteSeed(
        contentTr = "Ey sevgili okur, ba\u015fkalar\u0131nda g\u00f6rd\u00fc\u011f\u00fcn kusurlar\u0131n \u00e7o\u011fu, onlara yans\u0131yan kendi tabiat\u0131nd\u0131r.",
        contentEn = "Many of the faults you see in others, dear reader, are your own nature reflected in them.",
        source = "Rumi",
        referenceUrl = "https://en.wikiquote.org/wiki/Rumi",
    ),
    SystemQuoteSeed(
        contentTr = "D\u00fc\u015fman saflar\u0131n\u0131 yaran aslan, kendini yenen aslana k\u0131yasla k\u00fc\u00e7\u00fck bir kahramand\u0131r.",
        contentEn = "The lion who breaks the enemy's ranks is a minor hero compared to the lion who overcomes himself.",
        source = "Rumi",
        referenceUrl = "https://en.wikiquote.org/wiki/Rumi",
    ),
    SystemQuoteSeed(
        contentTr = "Vizyon sahibi insanlar olmasayd\u0131, k\u00f6rlerin hepsi \u00f6lm\u00fc\u015f olurdu.",
        contentEn = "Were there no men of vision, all who are blind would be dead.",
        source = "Rumi",
        referenceUrl = "https://en.wikiquote.org/wiki/Rumi",
    ),
    SystemQuoteSeed(
        contentTr = "K\u00fct\u00fcphaneler, eski azizlerin hakiki erdemle dolu b\u00fct\u00fcn kal\u0131nt\u0131lar\u0131n\u0131n, aldatma ve sahtek\u00e2rl\u0131k olmadan sakland\u0131\u011f\u0131 t\u00fcrbeler gibidir.",
        contentEn = "Libraries are as the shrine where all the relics of the ancient saints, full of true virtue, and that without delusion or imposture, are preserved and reposed.",
        source = "Francis Bacon",
        referenceUrl = "https://en.wikiquote.org/wiki/Francis_Bacon",
    ),
    SystemQuoteSeed(
        contentTr = "Zek\u00e2n\u0131n an\u0131tlar\u0131, iktidar\u0131n an\u0131tlar\u0131ndan daha uzun ya\u015far.",
        contentEn = "The monuments of wit survive the monuments of power.",
        source = "Francis Bacon",
        referenceUrl = "https://en.wikiquote.org/wiki/Francis_Bacon",
    ),
    SystemQuoteSeed(
        contentTr = "\u00c7\u00fcnk\u00fc bilginin kendisi g\u00fc\u00e7t\u00fcr.",
        contentEn = "For knowledge itself is power.",
        source = "Francis Bacon",
        referenceUrl = "https://en.wikiquote.org/wiki/Francis_Bacon",
    ),
    SystemQuoteSeed(
        contentTr = "Say\u0131 \u00e7oklu\u011fu, ordularda san\u0131ld\u0131\u011f\u0131 kadar \u00f6nemli de\u011fildir; \u00e7\u00fcnk\u00fc halk\u0131n y\u00fcre\u011fi zay\u0131fsa, kurt i\u00e7in koyunlar\u0131n say\u0131s\u0131 hi\u00e7 mesele olmaz.",
        contentEn = "Nay, number (itself) in armies, importeth not much, where the people is of weak courage; for (as Virgil saith) it never troubles the wolf how many the sheep be.",
        source = "Francis Bacon",
        referenceUrl = "https://en.wikiquote.org/wiki/Francis_Bacon",
    ),
    SystemQuoteSeed(
        contentTr = "Yaln\u0131zca tatmine y\u00f6nelen bilgi, meyve ya da \u00fcretim i\u00e7in de\u011fil haz i\u00e7in var olan bir metres gibidir.",
        contentEn = "Knowledge, that tendeth but to satisfaction, is but as a courtesan, which is for pleasure, and not for fruit or generation.",
        source = "Francis Bacon",
        referenceUrl = "https://en.wikiquote.org/wiki/Francis_Bacon",
    ),
    SystemQuoteSeed(
        contentTr = "Korkunun kendisinden ba\u015fka korkun\u00e7 bir \u015fey yoktur.",
        contentEn = "Nothing is terrible except fear itself.",
        source = "Francis Bacon",
        referenceUrl = "https://en.wikiquote.org/wiki/Francis_Bacon",
    ),
    SystemQuoteSeed(
        contentTr = "Zenginlik iyi bir hizmetk\u00e2r, ama en k\u00f6t\u00fc efendidir.",
        contentEn = "Riches are a good handmaid, but the worst mistress.",
        source = "Francis Bacon",
        referenceUrl = "https://en.wikiquote.org/wiki/Francis_Bacon",
    ),
    SystemQuoteSeed(
        contentTr = "\u0130ftiralar\u0131n\u0131 cesurca savur; elbet bir \u015fey yap\u0131\u015f\u0131r.",
        contentEn = "Hurl your calumnies boldly; something is sure to stick.",
        source = "Francis Bacon",
        referenceUrl = "https://en.wikiquote.org/wiki/Francis_Bacon",
    ),
    SystemQuoteSeed(
        contentTr = "Ruhumu Tanr\u0131'ya b\u0131rak\u0131yorum (...). Bedenimin g\u00f6steri\u015fsizce g\u00f6m\u00fclmesini istiyorum. Ad\u0131m\u0131 ve hat\u0131ram\u0131 ise insanlar\u0131n insafl\u0131 s\u00f6zlerine, yabanc\u0131 uluslara ve gelecek \u00e7a\u011fa b\u0131rak\u0131yorum.",
        contentEn = "I bequeath my soul to God (...). My body to be buried obscurely. For my name and memory, I leave it to men's charitable speeches, and to foreign nations, and the next age.",
        source = "Francis Bacon",
        referenceUrl = "https://en.wikiquote.org/wiki/Francis_Bacon",
    ),
    SystemQuoteSeed(
        contentTr = "Daha k\u0131sa bir mektup yazard\u0131m ama vaktim yoktu.",
        contentEn = "I would have written a shorter letter, but I did not have the time.",
        source = "Blaise Pascal",
        referenceUrl = "https://en.wikiquote.org/wiki/Blaise_Pascal",
    ),
    SystemQuoteSeed(
        contentTr = "\u0130nsanlar \u00e7o\u011fu zaman inan\u00e7lar\u0131na kan\u0131t temelinde de\u011fil, \u00e7ekici bulduklar\u0131 \u015fey temelinde var\u0131rlar.",
        contentEn = "People almost invariably arrive at their beliefs not on the basis of proof but on the basis of what they find attractive.",
        source = "Blaise Pascal",
        referenceUrl = "https://en.wikiquote.org/wiki/Blaise_Pascal",
    ),
    SystemQuoteSeed(
        contentTr = "Sahip oldu\u011fun servetin efendisi olman, o adam\u0131n kral olu\u015fundan daha az tesad\u00fcf de\u011fildir sanma.",
        contentEn = "Do not imagine that it is less an accident by which you find yourself master of the wealth which you possess, than that by which this man found himself king.",
        source = "Blaise Pascal",
        referenceUrl = "https://en.wikiquote.org/wiki/Blaise_Pascal",
    ),
    SystemQuoteSeed(
        contentTr = "M\u00fclk\u00fcn \u00fczerindeki b\u00fct\u00fcn hakk\u0131n, do\u011fan\u0131n de\u011fil insan kurumunun verdi\u011fi bir hakt\u0131r.",
        contentEn = "The whole title by which you possess your property, is not a title of nature but of a human institution.",
        source = "Blaise Pascal",
        referenceUrl = "https://en.wikiquote.org/wiki/Blaise_Pascal",
    ),
    SystemQuoteSeed(
        contentTr = "Kamusal d\u00fc\u015f\u00fcnce seni insanlar\u0131n geneli \u00fczerine \u00e7\u0131kar\u0131yorsa, \u00f6teki d\u00fc\u015f\u00fcnce seni al\u00e7alts\u0131n ve b\u00fct\u00fcn insanl\u0131kla tam bir e\u015fitlik i\u00e7inde tutsun; \u00e7\u00fcnk\u00fc senin do\u011fal durumun budur.",
        contentEn = "If the public thought elevates you above the generality of men, let the other humble you, and hold you in a perfect equality with all mankind, for this is your natural condition.",
        source = "Blaise Pascal",
        referenceUrl = "https://en.wikiquote.org/wiki/Blaise_Pascal",
    ),
    SystemQuoteSeed(
        contentTr = "Kendinde ba\u015fkalar\u0131ndan daha y\u00fcce bir \u00f6z bulundu\u011funa inanarak kendini aldatma.",
        contentEn = "Do not mistake yourself by believing that your being has something in it more exalted than that of others.",
        source = "Blaise Pascal",
        referenceUrl = "https://en.wikiquote.org/wiki/Blaise_Pascal",
    ),
    SystemQuoteSeed(
        contentTr = "\u0130nsan\u0131n, hakikate do\u011frudan sahip oldu\u011funu sanmas\u0131 do\u011fal bir hastal\u0131kt\u0131r.",
        contentEn = "It is a natural illness of man to think that he possesses the truth directly...",
        source = "Blaise Pascal",
        referenceUrl = "https://en.wikiquote.org/wiki/Blaise_Pascal",
    ),
    SystemQuoteSeed(
        contentTr = "Hi\u00e7 kimse, g\u00f6r\u00fc\u015flerin ruha iki ana yoldan girdi\u011fini bilmez de\u011fildir: bunlar onun iki ba\u015fl\u0131ca g\u00fcc\u00fc olan anlama ve istemedir.",
        contentEn = "No one is ignorant that there are two avenues by which opinions are received into the soul, which are its two principal powers: the understanding and the will.",
        source = "Blaise Pascal",
        referenceUrl = "https://en.wikiquote.org/wiki/Blaise_Pascal",
    ),
    SystemQuoteSeed(
        contentTr = "Tanr\u0131, \u0131\u015f\u0131\u011f\u0131n\u0131 zihne ancak iradenin isyan\u0131n\u0131, onu cezbeden ve kazanan b\u00fct\u00fcn\u00fcyle g\u00f6ksel bir yumu\u015fakl\u0131kla bast\u0131rd\u0131ktan sonra d\u00f6ker.",
        contentEn = "God only pours out his light into the mind after having subdued the rebellion of the will by an altogether heavenly gentleness which charms and wins it.",
        source = "Blaise Pascal",
        referenceUrl = "https://en.wikiquote.org/wiki/Blaise_Pascal",
    ),
    SystemQuoteSeed(
        contentTr = "S\u00f6yleyecek s\u00f6z\u00fc olmayan ki\u015fi daima k\u00f6t\u00fc konu\u015fur.",
        contentEn = "One always speaks badly when one has nothing to say.",
        source = "Voltaire",
        referenceUrl = "https://en.wikiquote.org/wiki/Voltaire",
    ),
    SystemQuoteSeed(
        contentTr = "Halk vah\u015fi bir canavard\u0131r: ya zincire vurmal\u0131 ya ondan ka\u00e7mal\u0131d\u0131r.",
        contentEn = "The public is a ferocious beast: one must chain it up or flee from it.",
        source = "Voltaire",
        referenceUrl = "https://en.wikiquote.org/wiki/Voltaire",
    ),
    SystemQuoteSeed(
        contentTr = "Tutkular\u0131n en g\u00fc\u00e7l\u00fcs\u00fc a\u015fkt\u0131r; \u00e7\u00fcnk\u00fc ayn\u0131 anda ba\u015fa, kalbe ve bedene sald\u0131r\u0131r.",
        contentEn = "Love is of all the passions the strongest, for it attacks simultaneously the head, the heart, and the body.",
        source = "Voltaire",
        referenceUrl = "https://en.wikiquote.org/wiki/Voltaire",
    ),
    SystemQuoteSeed(
        contentTr = "Erdem, kendini hakl\u0131 \u00e7\u0131karma ile de\u011fersizle\u015fir.",
        contentEn = "Virtue is debased by self-justification.",
        source = "Voltaire",
        referenceUrl = "https://en.wikiquote.org/wiki/Voltaire",
    ),
    SystemQuoteSeed(
        contentTr = "Ya\u015fayanlara kar\u015f\u0131 d\u00fc\u015f\u00fcnceli olmal\u0131y\u0131z; \u00f6l\u00fclere kar\u015f\u0131 tek borcumuz ise hakikattir.",
        contentEn = "We should be considerate to the living; to the dead we owe only the truth.",
        source = "Voltaire",
        referenceUrl = "https://en.wikiquote.org/wiki/Voltaire",
    ),
    SystemQuoteSeed(
        contentTr = "Pek a\u011f\u0131r bir y\u00fckt\u00fcr, fazla \u00e7abuk gelen \u015f\u00f6hret.",
        contentEn = "Quite a heavy weight, a name too quickly famous.",
        source = "Voltaire",
        referenceUrl = "https://en.wikiquote.org/wiki/Voltaire",
    ),
    SystemQuoteSeed(
        contentTr = "\u0130nsan, istedi\u011fi anda \u00f6zg\u00fcrd\u00fcr.",
        contentEn = "Man is free at the instant he wants to be.",
        source = "Voltaire",
        referenceUrl = "https://en.wikiquote.org/wiki/Voltaire",
    ),
    SystemQuoteSeed(
        contentTr = "B\u00fct\u00fcn \u00f6l\u00fcml\u00fcler e\u015fittir; onlar\u0131 ay\u0131ran do\u011fumlar\u0131 de\u011fil, erdemleridir.",
        contentEn = "All mortals are equal; it is not their birth, but virtue itself that makes the difference.",
        source = "Voltaire",
        referenceUrl = "https://en.wikiquote.org/wiki/Voltaire",
    ),
    SystemQuoteSeed(
        contentTr = "Eski Romal\u0131lar mimarinin en b\u00fcy\u00fck eserlerini vah\u015fi hayvanlar\u0131n d\u00f6v\u00fc\u015fmesi i\u00e7in in\u015fa ettiler.",
        contentEn = "The ancient Romans built their greatest masterpieces of architecture for wild beasts to fight in.",
        source = "Voltaire",
        referenceUrl = "https://en.wikiquote.org/wiki/Voltaire",
    ),
    SystemQuoteSeed(
        contentTr = "I\u015f\u0131\u011f\u0131n \u00e7ok oldu\u011fu yerde g\u00f6lge de g\u00fc\u00e7l\u00fcd\u00fcr.",
        contentEn = "There is strong shadow where there is much light.",
        source = "Johann Wolfgang von Goethe",
        referenceUrl = "https://en.wikiquote.org/wiki/Johann_Wolfgang_von_Goethe",
    ),
    SystemQuoteSeed(
        contentTr = "Yaln\u0131zca kendi ba\u011f\u0131ms\u0131z yerini dolduran, ne buyurmak ne de boyun e\u011fmek zorunda olan ki\u015fi ger\u00e7ekten b\u00fcy\u00fck ve mutludur.",
        contentEn = "He alone is great and happy who fills his own station of independence, and has neither to command nor to obey.",
        source = "Johann Wolfgang von Goethe",
        referenceUrl = "https://en.wikiquote.org/wiki/Johann_Wolfgang_von_Goethe",
    ),
    SystemQuoteSeed(
        contentTr = "\u0130nsan d\u00fcnyada yaln\u0131zca bir kez ya\u015far.",
        contentEn = "One lives but once in the world.",
        source = "Johann Wolfgang von Goethe",
        referenceUrl = "https://en.wikiquote.org/wiki/Johann_Wolfgang_von_Goethe",
    ),
    SystemQuoteSeed(
        contentTr = "Gen\u00e7ken insan, insanl\u0131k i\u00e7in saraylar kurabilece\u011fine inan\u0131r; zaman\u0131 gelince elleri, onlar\u0131n \u00e7\u00f6p\u00fcn\u00fc temizlemeye ancak yeter.",
        contentEn = "When young, one is confident to be able to build palaces for mankind, but when the time comes one has one's hands full just to be able to remove their trash.",
        source = "Johann Wolfgang von Goethe",
        referenceUrl = "https://en.wikiquote.org/wiki/Johann_Wolfgang_von_Goethe",
    ),
    SystemQuoteSeed(
        contentTr = "B\u00fcy\u00fck, ebedi, elmas sertli\u011findeki yasalar buyurur: hepimiz varolu\u015fumuzun d\u00f6ng\u00fclerini tamamlamak zorunday\u0131z.",
        contentEn = "As great, everlasting, Adamantine laws Dictate, we must all Complete the cycles Of our existence.",
        source = "Johann Wolfgang von Goethe",
        referenceUrl = "https://en.wikiquote.org/wiki/Johann_Wolfgang_von_Goethe",
    ),
    SystemQuoteSeed(
        contentTr = "\u0130mk\u00e2ns\u0131z\u0131 yapabilen yaln\u0131zca insand\u0131r: ay\u0131rt eder, se\u00e7er ve yarg\u0131lar; ana kal\u0131c\u0131l\u0131k verebilir.",
        contentEn = "Only mankind Can do the impossible: He can distinguish, He chooses and judges, He can give permanence To the moment.",
        source = "Johann Wolfgang von Goethe",
        referenceUrl = "https://en.wikiquote.org/wiki/Johann_Wolfgang_von_Goethe",
    ),
    SystemQuoteSeed(
        contentTr = "Soylu insan c\u00f6mert ve iyi olsun; durmaks\u0131z\u0131n adil ve yararl\u0131 olan\u0131 ger\u00e7ekle\u015ftirsin; varl\u0131\u011f\u0131n\u0131 sezdi\u011fi varl\u0131klar i\u00e7in \u00f6rnek olsun.",
        contentEn = "Let the noble man Be generous and good, Tirelessly achieving What is just and useful: Let him be a model For those beings whom he surmises.",
        source = "Johann Wolfgang von Goethe",
        referenceUrl = "https://en.wikiquote.org/wiki/Johann_Wolfgang_von_Goethe",
    ),
    SystemQuoteSeed(
        contentTr = "Sanatta en iyisi, yeterince iyidir.",
        contentEn = "In art the best is good enough.",
        source = "Johann Wolfgang von Goethe",
        referenceUrl = "https://en.wikiquote.org/wiki/Johann_Wolfgang_von_Goethe",
    ),
    SystemQuoteSeed(
        contentTr = "Soylu ki\u015fi, soylu insanlar\u0131 kendine \u00e7eker ve onlar\u0131 elinde tutmay\u0131 bilir.",
        contentEn = "A noble person attracts noble people, and knows how to hold on to them.",
        source = "Johann Wolfgang von Goethe",
        referenceUrl = "https://en.wikiquote.org/wiki/Johann_Wolfgang_von_Goethe",
    ),
    SystemQuoteSeed(
        contentTr = "\u00c2\u015f\u0131k olan ki\u015fi bilgedir ve daha da bilgele\u015fir; sevdi\u011fi \u015feye her bakt\u0131\u011f\u0131nda onu yeniden g\u00f6r\u00fcr, g\u00f6zlerinden ve zihninden ondaki erdemleri \u00e7eker.",
        contentEn = "He who is in love is wise and is becoming wiser, sees newly every time he looks at the object beloved, drawing from it with his eyes and his mind those virtues which it possesses.",
        source = "Ralph Waldo Emerson",
        referenceUrl = "https://en.wikiquote.org/wiki/Ralph_Waldo_Emerson",
    ),
    SystemQuoteSeed(
        contentTr = "\u0130nsan, d\u00fcr\u00fcstl\u00fc\u011f\u00fcn\u00fc ya da akl\u0131n\u0131 yitirmeden de bir paradoksu sevebilir.",
        contentEn = "Yet a man may love a paradox, without losing either his wit or his honesty.",
        source = "Ralph Waldo Emerson",
        referenceUrl = "https://en.wikiquote.org/wiki/Ralph_Waldo_Emerson",
    ),
    SystemQuoteSeed(
        contentTr = "Edebiyat, insan\u0131n kendi durumunun haks\u0131zl\u0131klar\u0131n\u0131 telafi etme \u00e7abas\u0131d\u0131r.",
        contentEn = "Literature is the effort of man to indemnify himself for the wrongs of his condition.",
        source = "Ralph Waldo Emerson",
        referenceUrl = "https://en.wikiquote.org/wiki/Ralph_Waldo_Emerson",
    ),
    SystemQuoteSeed(
        contentTr = "Kendine dayanmak, insan\u0131n zirvesi ve m\u00fckemmelli\u011fidir; Tanr\u0131'ya dayanmakt\u0131r.",
        contentEn = "Self-reliance, the height and perfection of man, is reliance on God.",
        source = "Ralph Waldo Emerson",
        referenceUrl = "https://en.wikiquote.org/wiki/Ralph_Waldo_Emerson",
    ),
    SystemQuoteSeed(
        contentTr = "\u015eiir, az say\u0131da s\u00f6z\u00fcn muazzam g\u00fcc\u00fcn\u00fc \u00f6\u011fretir; ilham artt\u0131k\u00e7a gevezeli\u011fi frenler.",
        contentEn = "Poetry teaches the enormous force of a few words, and, in proportion to the inspiration, checks loquacity.",
        source = "Ralph Waldo Emerson",
        referenceUrl = "https://en.wikiquote.org/wiki/Ralph_Waldo_Emerson",
    ),
    SystemQuoteSeed(
        contentTr = "\u015eairlerin iki t\u00fcr\u00fc vard\u0131r: e\u011fitim ve \u00e7al\u0131\u015fma ile \u015fair olanlar, bunlara sayg\u0131 duyar\u0131z; do\u011fas\u0131 gere\u011fi \u015fair olanlar ise sevilir.",
        contentEn = "There are two classes of poets \u2014 the poets by education and practice, these we respect; and poets by nature, these we love.",
        source = "Ralph Waldo Emerson",
        referenceUrl = "https://en.wikiquote.org/wiki/Ralph_Waldo_Emerson",
    ),
    SystemQuoteSeed(
        contentTr = "Ot nedir? Erdemleri hen\u00fcz ke\u015ffedilmemi\u015f bir bitki.",
        contentEn = "What is a weed? A plant whose virtues have yet to be discovered.",
        source = "Ralph Waldo Emerson",
        referenceUrl = "https://en.wikiquote.org/wiki/Ralph_Waldo_Emerson",
    ),
    SystemQuoteSeed(
        contentTr = "Farkl\u0131 zihinler i\u00e7in ayn\u0131 d\u00fcnya, birine cehennem, \u00f6tekine cennettir.",
        contentEn = "To different minds, the same world is a hell, and a heaven.",
        source = "Ralph Waldo Emerson",
        referenceUrl = "https://en.wikiquote.org/wiki/Ralph_Waldo_Emerson",
    ),
    SystemQuoteSeed(
        contentTr = "B\u00fct\u00fcn bir ulus var g\u00fcc\u00fcyle yurtseverlik diye ba\u011f\u0131r\u0131rken, ben ellerinin temizli\u011fini ve y\u00fcre\u011finin safl\u0131\u011f\u0131n\u0131 yoklamak isterim.",
        contentEn = "When a whole nation is roaring Patriotism at the top of its voice, I am fain to explore the cleanness of its hands and purity of its heart.",
        source = "Ralph Waldo Emerson",
        referenceUrl = "https://en.wikiquote.org/wiki/Ralph_Waldo_Emerson",
    ),
    SystemQuoteSeed(
        contentTr = "Bir olgunun de\u011ferini k\u00fc\u00e7\u00fcmsemeyelim; bir g\u00fcn hakikate \u00e7i\u00e7ek a\u00e7acakt\u0131r.",
        contentEn = "Let us not underrate the value of a fact; it will one day flower in a truth.",
        source = "Henry David Thoreau",
        referenceUrl = "https://en.wikiquote.org/wiki/Henry_David_Thoreau",
    ),
    SystemQuoteSeed(
        contentTr = "D\u00fcnya ne zaman \u00f6\u011frenecek ki bir milyon insan\u0131n \u00f6nemi, tek bir insan\u0131n \u00f6nemiyle k\u0131yaslanamaz?",
        contentEn = "When will the world learn that a million men are of no importance compared with one man?",
        source = "Henry David Thoreau",
        referenceUrl = "https://en.wikiquote.org/wiki/Henry_David_Thoreau",
    ),
    SystemQuoteSeed(
        contentTr = "Yasa insanlar\u0131 asla \u00f6zg\u00fcr k\u0131lamaz; yasay\u0131 \u00f6zg\u00fcr k\u0131lmas\u0131 gereken insanlard\u0131r.",
        contentEn = "The law will never make men free; it is men who have got to make the law free.",
        source = "Henry David Thoreau",
        referenceUrl = "https://en.wikiquote.org/wiki/Henry_David_Thoreau",
    ),
    SystemQuoteSeed(
        contentTr = "\u00c7al\u0131\u015fkan olmak yetmez; kar\u0131ncalar da \u00e7al\u0131\u015fkand\u0131r. Sen ne u\u011fruna \u00e7al\u0131\u015fkans\u0131n?",
        contentEn = "It is not enough to be industrious; so are the ants. What are you industrious about?",
        source = "Henry David Thoreau",
        referenceUrl = "https://en.wikiquote.org/wiki/Henry_David_Thoreau",
    ),
    SystemQuoteSeed(
        contentTr = "T\u00fcfek sana ku\u015fu de\u011fil, yaln\u0131zca g\u00f6vdesini verir.",
        contentEn = "A gun gives you the body, not the bird.",
        source = "Henry David Thoreau",
        referenceUrl = "https://en.wikiquote.org/wiki/Henry_David_Thoreau",
    ),
    SystemQuoteSeed(
        contentTr = "Bizim takdir etti\u011fimiz erdem, o kadar bizimdir ki ba\u015fkas\u0131n\u0131nki de olur. Ancak sahip oldu\u011fumuz kadar\u0131n\u0131 g\u00f6rebiliriz.",
        contentEn = "That virtue we appreciate is as much ours as another's. We see so much only as we possess.",
        source = "Henry David Thoreau",
        referenceUrl = "https://en.wikiquote.org/wiki/Henry_David_Thoreau",
    ),
    SystemQuoteSeed(
        contentTr = "Sabah\u0131n erken saatlerinde yap\u0131lan bir y\u00fcr\u00fcy\u00fc\u015f, b\u00fct\u00fcn g\u00fcn i\u00e7in bir nimettir.",
        contentEn = "An early morning walk is a blessing for the whole day.",
        source = "Henry David Thoreau",
        referenceUrl = "https://en.wikiquote.org/wiki/Henry_David_Thoreau",
    ),
    SystemQuoteSeed(
        contentTr = "Ne kadar g\u00f6r\u00fcyorsak o kadar\u0131z. \u0130nan\u00e7 da bilgi de g\u00f6rmektir. Eller yaln\u0131zca g\u00f6zlere hizmet eder.",
        contentEn = "We are as much as we see. Faith is sight and knowledge. The hands only serve the eyes.",
        source = "Henry David Thoreau",
        referenceUrl = "https://en.wikiquote.org/wiki/Henry_David_Thoreau",
    ),
    SystemQuoteSeed(
        contentTr = "Ama\u00e7s\u0131zca dola\u015fmak b\u00fcy\u00fck bir sanatt\u0131r.",
        contentEn = "It is a great art to saunter.",
        source = "Henry David Thoreau",
        referenceUrl = "https://en.wikiquote.org/wiki/Henry_David_Thoreau",
    ),
    SystemQuoteSeed(
        contentTr = "Do\u011frunun cinsiyeti yoktur, hakikatin rengi yoktur, Tanr\u0131 hepimizin Babas\u0131d\u0131r ve hepimiz karde\u015fiz.",
        contentEn = "Right is of no sex, Truth is of no color, God is the Father of us all, and we are all Brethren.",
        source = "Frederick Douglass",
        referenceUrl = "https://en.wikiquote.org/wiki/Frederick_Douglass",
    ),
    SystemQuoteSeed(
        contentTr = "Hakl\u0131 olan adam \u00e7o\u011funluktur. Tanr\u0131 ve vicdan bizim yan\u0131m\u0131zdaysa, evrene kar\u015f\u0131 bile \u00e7o\u011funlu\u011fuzdur.",
        contentEn = "The man who is right is a majority. We, who have God and conscience on our side, have a majority against the universe.",
        source = "Frederick Douglass",
        referenceUrl = "https://en.wikiquote.org/wiki/Frederick_Douglass",
    ),
    SystemQuoteSeed(
        contentTr = "Her ezgi, k\u00f6leli\u011fe kar\u015f\u0131 bir tan\u0131kl\u0131k ve zincirlerden kurtulu\u015f i\u00e7in Tanr\u0131'ya y\u00fckselen bir duayd\u0131.",
        contentEn = "Every tone was a testimony against slavery, and a prayer to God for deliverance from chains.",
        source = "Frederick Douglass",
        referenceUrl = "https://en.wikiquote.org/wiki/Frederick_Douglass",
    ),
    SystemQuoteSeed(
        contentTr = "Bir insan\u0131n nas\u0131l k\u00f6le yap\u0131ld\u0131\u011f\u0131n\u0131 g\u00f6rd\u00fcn\u00fcz; \u015fimdi de bir k\u00f6lenin nas\u0131l insan yap\u0131ld\u0131\u011f\u0131n\u0131 g\u00f6receksiniz.",
        contentEn = "You have seen how a man was made a slave; you shall see how a slave was made a man.",
        source = "Frederick Douglass",
        referenceUrl = "https://en.wikiquote.org/wiki/Frederick_Douglass",
    ),
    SystemQuoteSeed(
        contentTr = "Zorba olana hi\u00e7bir yard\u0131m sunmayal\u0131m; u\u00e7an karde\u015fimizin izini s\u00fcrebilmesi i\u00e7in \u0131\u015f\u0131\u011f\u0131 onun elinde tutmayal\u0131m.",
        contentEn = "Let us render the tyrant no aid; let us not hold the light by which he can trace the footprints of our flying brother.",
        source = "Frederick Douglass",
        referenceUrl = "https://en.wikiquote.org/wiki/Frederick_Douglass",
    ),
    SystemQuoteSeed(
        contentTr = "Bu \u00fclkede siyah bir insan\u0131n bast\u0131\u011f\u0131 topra\u011f\u0131n her kar\u0131\u015f\u0131 sert\u00e7e tart\u0131\u015fmal\u0131d\u0131r.",
        contentEn = "The ground which a colored man occupies in this country is, every inch of it, sternly disputed.",
        source = "Frederick Douglass",
        referenceUrl = "https://en.wikiquote.org/wiki/Frederick_Douglass",
    ),
    SystemQuoteSeed(
        contentTr = "Do\u011fru olan\u0131 yapmak i\u00e7in herkesle birle\u015firim; yanl\u0131\u015f olan\u0131 yapmak i\u00e7inse hi\u00e7 kimseyle.",
        contentEn = "I would unite with anybody to do right; and with nobody to do wrong.",
        source = "Frederick Douglass",
        referenceUrl = "https://en.wikiquote.org/wiki/Frederick_Douglass",
    ),
    SystemQuoteSeed(
        contentTr = "\u00d6zg\u00fcrl\u00fc\u011fe sahip olaca\u011f\u0131m; olmazsa onu kazanma u\u011fruna \u00f6lece\u011fim.",
        contentEn = "Liberty I will have, or die in the attempt to gain it.",
        source = "Frederick Douglass",
        referenceUrl = "https://en.wikiquote.org/wiki/Frederick_Douglass",
    ),
    SystemQuoteSeed(
        contentTr = "K\u00f6lelikle g\u00f6r\u00fcn\u00fcrdeki ho\u015fnutluk nerede varsa, \u00f6zg\u00fcrl\u00fc\u011fe kar\u015f\u0131 kesin bir ihanet oradad\u0131r.",
        contentEn = "Where there is seeming contentment with slavery, there is certain treachery to freedom.",
        source = "Frederick Douglass",
        referenceUrl = "https://en.wikiquote.org/wiki/Frederick_Douglass",
    ),
    SystemQuoteSeed(
        contentTr = "Ben al\u0131\u015f\u0131lm\u0131\u015f yolda y\u00fcr\u00fcmek i\u00e7in do\u011fmad\u0131m; tabiat\u0131m\u0131n kendine \u00f6zg\u00fc e\u011filimi beni ileri iter.",
        contentEn = "You know I am not born to tread in the beaten track \u2014 the peculiar bent of my nature pushes me on.",
        source = "Mary Wollstonecraft",
        referenceUrl = "https://en.wikiquote.org/wiki/Mary_Wollstonecraft",
    ),
    SystemQuoteSeed(
        contentTr = "Erdem ancak e\u015fitler aras\u0131nda ye\u015ferir.",
        contentEn = "Virtue can only flourish amongst equals.",
        source = "Mary Wollstonecraft",
        referenceUrl = "https://en.wikiquote.org/wiki/Mary_Wollstonecraft",
    ),
    SystemQuoteSeed(
        contentTr = "Her siyasal iyilik, a\u015f\u0131r\u0131ya g\u00f6t\u00fcr\u00fcld\u00fc\u011f\u00fcnde k\u00f6t\u00fcl\u00fck \u00fcretir.",
        contentEn = "Every political good carried to the extreme must be productive of evil.",
        source = "Mary Wollstonecraft",
        referenceUrl = "https://en.wikiquote.org/wiki/Mary_Wollstonecraft",
    ),
    SystemQuoteSeed(
        contentTr = "Ya\u015f\u0131n\u0131 doldurmu\u015f bir d\u00fczeni yapay bi\u00e7imde ayakta tutmaya \u00e7al\u0131\u015fmak \u00e7o\u011fu zaman zararl\u0131d\u0131r ve her zaman bo\u015ftur.",
        contentEn = "The endeavor to keep alive any hoary establishment beyond its natural date is often pernicious and always useless.",
        source = "Mary Wollstonecraft",
        referenceUrl = "https://en.wikiquote.org/wiki/Mary_Wollstonecraft",
    ),
    SystemQuoteSeed(
        contentTr = "Sanat insanlar\u0131n duyguda\u015fl\u0131\u011f\u0131n\u0131 b\u00fcy\u00fctm\u00fcyorsa, ahlaken hi\u00e7bir \u015fey yapm\u0131yor demektir.",
        contentEn = "If art does not enlarge men's sympathies, it does nothing morally.",
        source = "George Eliot",
        referenceUrl = "https://en.wikiquote.org/wiki/George_Eliot",
    ),
    SystemQuoteSeed(
        contentTr = "'Ba\u015far\u0131s\u0131zl\u0131k' s\u00f6z\u00fc bana i\u015flemez. Onun arkas\u0131n\u0131 g\u00f6rd\u00fcm. Bir insan\u0131n korkmas\u0131 gereken tek ba\u015far\u0131s\u0131zl\u0131k, en iyi g\u00f6rd\u00fc\u011f\u00fc amaca sad\u0131k kalamamakt\u0131r.",
        contentEn = "I'm proof against that word failure. I've seen behind it. The only failure a man ought to fear is failure of cleaving to the purpose he sees to be best.",
        source = "George Eliot",
        referenceUrl = "https://en.wikiquote.org/wiki/George_Eliot",
    ),
    SystemQuoteSeed(
        contentTr = "Bir se\u00e7im yakla\u015f\u0131yor. Evrensel bar\u0131\u015f ilan edildi; tilkiler de k\u00fcmes hayvanlar\u0131n\u0131n \u00f6mr\u00fcn\u00fc uzatma konusunda son derece samimi g\u00f6r\u00fcn\u00fcyor.",
        contentEn = "An election is coming. Universal peace is declared, and the foxes have a sincere interest in prolonging the lives of the poultry.",
        source = "George Eliot",
        referenceUrl = "https://en.wikiquote.org/wiki/George_Eliot",
    ),
    SystemQuoteSeed(
        contentTr = "Ne mutlu, s\u00f6yleyecek hi\u00e7bir \u015feyi olmad\u0131\u011f\u0131 h\u00e2lde bunu gevezelik ederek kan\u0131tlamaktan ka\u00e7\u0131nan insana.",
        contentEn = "Blessed is the man who, having nothing to say, abstains from giving us wordy evidence of the fact.",
        source = "George Eliot",
        referenceUrl = "https://en.wikiquote.org/wiki/George_Eliot",
    ),
    SystemQuoteSeed(
        contentTr = "Hayat \u0131rma\u011f\u0131ndaki alt\u0131n anlar ak\u0131p gider, bizse sadece kumu g\u00f6r\u00fcr\u00fcz; melekler bizi ziyaret eder, biz onlar\u0131 ancak gittiklerinde tan\u0131r\u0131z.",
        contentEn = "The golden moments in the stream of life rush past us, and we see nothing but sand; the angels come to visit us, and we only know them when they are gone.",
        source = "George Eliot",
        referenceUrl = "https://en.wikiquote.org/wiki/George_Eliot",
    ),
    SystemQuoteSeed(
        contentTr = "Birbirimizin hayat\u0131n\u0131 daha az zorla\u015ft\u0131rmak de\u011filse, ne i\u00e7in ya\u015f\u0131yoruz?",
        contentEn = "What do we live for, if it is not to make life less difficult for each other?",
        source = "George Eliot",
        referenceUrl = "https://en.wikiquote.org/wiki/George_Eliot",
    ),
    SystemQuoteSeed(
        contentTr = "Zorluk, kararl\u0131l\u0131\u011f\u0131n etkinli\u011fe mi yoksa daha olumsuz bir h\u00e2li kabullenmeye mi y\u00f6nelmesi gerekti\u011fine karar vermektir.",
        contentEn = "The difficulty is, to decide how far resolution should set in the direction of activity rather than in the acceptance of a more negative state.",
        source = "George Eliot",
        referenceUrl = "https://en.wikiquote.org/wiki/George_Eliot",
    ),
    SystemQuoteSeed(
        contentTr = "Durmadan \u015funu dileyeyim: \u00e7evremdeki her \u015feyi onun geleneksel, insani, ge\u00e7ici giysisinden soyup \u00f6z\u00fcnde ve sonsuzlukla ili\u015fkisinde g\u00f6rebileyim.",
        contentEn = "May I unceasingly aspire to unclothe all around me of its conventional, human, temporary dress, to look at it in its essence and in its relation to eternity.",
        source = "George Eliot",
        referenceUrl = "https://en.wikiquote.org/wiki/George_Eliot",
    ),
    SystemQuoteSeed(
        contentTr = "Canavar, matematik\u00e7i ya da \u00e7\u0131lg\u0131n filozof olmayan her erkek, \u015fu ya da bu bi\u00e7imde bir kad\u0131n\u0131n k\u00f6lesidir.",
        contentEn = "Every man who is not a monster, a mathematician, or a mad philosopher, is the slave of some woman or other.",
        source = "George Eliot",
        referenceUrl = "https://en.wikiquote.org/wiki/George_Eliot",
    ),
    SystemQuoteSeed(
        contentTr = "Masal\u0131m\u0131n kahraman\u0131, ruhumun b\u00fct\u00fcn g\u00fcc\u00fcyle sevdi\u011fim, b\u00fct\u00fcn g\u00fczelli\u011fiyle tasvir etmeye \u00e7al\u0131\u015ft\u0131\u011f\u0131m, olmu\u015f, olan ve olacak olan \u015fey Hakikat'tir.",
        contentEn = "The hero of my tale, whom I love with all the power of my soul, whom I have tried to portray in all his beauty, who has been, is, and will be beautiful, is Truth.",
        source = "Leo Tolstoy",
        referenceUrl = "https://en.wikiquote.org/wiki/Leo_Tolstoy",
    ),
    SystemQuoteSeed(
        contentTr = "\u0130nsanlarla birli\u011fimin, ulusal s\u0131n\u0131rlar ve devlet buyruklar\u0131yla yok edilemeyece\u011fini biliyorum.",
        contentEn = "I know that my unity with all people cannot be destroyed by national boundaries and government orders.",
        source = "Leo Tolstoy",
        referenceUrl = "https://en.wikiquote.org/wiki/Leo_Tolstoy",
    ),
    SystemQuoteSeed(
        contentTr = "\u0130htiya\u00e7 duydu\u011fu tek \u015fey alt\u0131 kar\u0131\u015f toprakt\u0131.",
        contentEn = "Six feet of land was all that he needed.",
        source = "Leo Tolstoy",
        referenceUrl = "https://en.wikiquote.org/wiki/Leo_Tolstoy",
    ),
    SystemQuoteSeed(
        contentTr = "\u0130nsanlar\u0131n mutlulu\u011fu ya\u015fam\u0131n i\u00e7indedir; ya\u015fam da eme\u011fin i\u00e7indedir.",
        contentEn = "The happiness of men consists in life. And life is in labor.",
        source = "Leo Tolstoy",
        referenceUrl = "https://en.wikiquote.org/wiki/Leo_Tolstoy",
    ),
    SystemQuoteSeed(
        contentTr = "Her erke\u011fin ve her kad\u0131n\u0131n g\u00f6revi, ba\u015fka insanlara hizmet etmektir.",
        contentEn = "The vocation of every man and woman is to serve other people.",
        source = "Leo Tolstoy",
        referenceUrl = "https://en.wikiquote.org/wiki/Leo_Tolstoy",
    ),
    SystemQuoteSeed(
        contentTr = "\u0130nsana ne kadar \u00e7ok verilirse, insanlar kendileri i\u00e7in o kadar az \u00e7al\u0131\u015facakt\u0131r; kendileri i\u00e7in ne kadar az \u00e7al\u0131\u015f\u0131rlarsa, yoksulluklar\u0131 da o kadar artacakt\u0131r.",
        contentEn = "The more is given the less the people will work for themselves, and the less they work the more their poverty will increase.",
        source = "Leo Tolstoy",
        referenceUrl = "https://en.wikiquote.org/wiki/Leo_Tolstoy",
    ),
    SystemQuoteSeed(
        contentTr = "\u0130sterseniz beni mahk\u00fbm edin \u2014 bunu ben zaten kendime yap\u0131yorum \u2014 ama beni mahk\u00fbm edin, izledi\u011fim ve bana soranlara yolun bu oldu\u011funu s\u00f6yledi\u011fim yolu de\u011fil.",
        contentEn = "Condemn me if you choose \u2014 I do that myself, \u2014 but condemn me, and not the path which I am following, and which I point out to those who ask me where, in my opinion, the path is.",
        source = "Leo Tolstoy",
        referenceUrl = "https://en.wikiquote.org/wiki/Leo_Tolstoy",
    ),
    SystemQuoteSeed(
        contentTr = "B\u00fct\u00fcn \u015fiddet, baz\u0131 insanlar\u0131n ba\u015fkalar\u0131n\u0131, ac\u0131 \u00e7ekme ya da \u00f6l\u00fcm tehdidi alt\u0131nda, istemedikleri \u015feyi yapmaya zorlamas\u0131ndan ibarettir.",
        contentEn = "All violence consists in some people forcing others, under threat of suffering or death, to do what they do not want to do.",
        source = "Leo Tolstoy",
        referenceUrl = "https://en.wikiquote.org/wiki/Leo_Tolstoy",
    ),
    SystemQuoteSeed(
        contentTr = "Bilim anlams\u0131zd\u0131r; \u00e7\u00fcnk\u00fc bizim i\u00e7in tek \u00f6nemli soruya, 'Ne yapmal\u0131y\u0131z ve nas\u0131l ya\u015famal\u0131y\u0131z?' sorusuna cevap vermez.",
        contentEn = "Science is meaningless because it gives no answer to our question, the only question important for us: 'what shall we do and how shall we live?'",
        source = "Leo Tolstoy",
        referenceUrl = "https://en.wikiquote.org/wiki/Leo_Tolstoy",
    ),
    SystemQuoteSeed(
        contentTr = "Kelebek aylar\u0131 de\u011fil anlar\u0131 sayar, yine de ona zaman yeter.",
        contentEn = "The butterfly counts not months but moments, and has time enough.",
        source = "Rabindranath Tagore",
        referenceUrl = "https://en.wikiquote.org/wiki/Rabindranath_Tagore",
    ),
    SystemQuoteSeed(
        contentTr = "Hakikat bize ancak fatih gibi gelir; \u00e7\u00fcnk\u00fc onu misafir gibi kar\u015f\u0131lamay\u0131 unuttuk.",
        contentEn = "The truth comes as conqueror only because we have lost the art of receiving it as guest.",
        source = "Rabindranath Tagore",
        referenceUrl = "https://en.wikiquote.org/wiki/Rabindranath_Tagore",
    ),
    SystemQuoteSeed(
        contentTr = "B\u00fcy\u00fck Veren Tanr\u0131, b\u00fct\u00fcn evreni g\u00f6z\u00fcm\u00fcze tek bir \u00fclkenin dar alan\u0131nda a\u00e7abilir.",
        contentEn = "God, the Great Giver, can open the whole universe to our gaze in the narrow space of a single land.",
        source = "Rabindranath Tagore",
        referenceUrl = "https://en.wikiquote.org/wiki/Rabindranath_Tagore",
    ),
    SystemQuoteSeed(
        contentTr = "Bor\u00e7lar\u0131m b\u00fcy\u00fck, ba\u015far\u0131s\u0131zl\u0131klar\u0131m \u00e7ok, utanc\u0131m gizli ve a\u011f\u0131r; yine de iyili\u011fimi istemeye geliyorum, duam kabul olur diye korkudan titriyorum.",
        contentEn = "My debts are large, my failures great, my shame secret and heavy; yet I come to ask for my good, I quake in fear lest my prayer be granted.",
        source = "Rabindranath Tagore",
        referenceUrl = "https://en.wikiquote.org/wiki/Rabindranath_Tagore",
    ),
    SystemQuoteSeed(
        contentTr = "Eski s\u00f6zler dilden d\u00fc\u015f\u00fcnce, kalpten yeni ezgiler do\u011far; eski izler kayboldu\u011funda ise harikalar\u0131yla yeni bir \u00fclke a\u00e7\u0131\u011fa \u00e7\u0131kar.",
        contentEn = "When old words die out on the tongue, new melodies break forth from the heart; and where the old tracks are lost, new country is revealed with its wonders.",
        source = "Rabindranath Tagore",
        referenceUrl = "https://en.wikiquote.org/wiki/Rabindranath_Tagore",
    ),
    SystemQuoteSeed(
        contentTr = "Sonsuz bi\u00e7imlerin bu oyun evinde ben de oyunumu oynad\u0131m ve burada bi\u00e7imsiz olan\u0131n bir anl\u0131k g\u00f6r\u00fcn\u00fc\u015f\u00fcn\u00fc yakalad\u0131m.",
        contentEn = "In this playhouse of infinite forms I have had my play, and here have I caught sight of him that is formless.",
        source = "Rabindranath Tagore",
        referenceUrl = "https://en.wikiquote.org/wiki/Rabindranath_Tagore",
    ),
    SystemQuoteSeed(
        contentTr = "Bi\u00e7imlerin okyanusunun derinli\u011fine dal\u0131yorum; umudum, bi\u00e7imsizin kusursuz incisini bulmak.",
        contentEn = "I dive down into the depth of the ocean of forms, hoping to gain the perfect pearl of the formless.",
        source = "Rabindranath Tagore",
        referenceUrl = "https://en.wikiquote.org/wiki/Rabindranath_Tagore",
    ),
    SystemQuoteSeed(
        contentTr = "Y\u0131ld\u0131zlar\u0131n \u0131\u015f\u0131\u011f\u0131 d\u00fcnyaya ula\u015fmak i\u00e7in milyonlarca mil yol al\u0131r, ama kalplerimize ula\u015famaz; onlara g\u00f6re \u00e7ok daha uza\u011f\u0131zd\u0131r.",
        contentEn = "The light of the stars travels millions of miles to reach the earth, but it cannot reach our hearts \u2014 so many millions of miles further off are we!",
        source = "Rabindranath Tagore",
        referenceUrl = "https://en.wikiquote.org/wiki/Rabindranath_Tagore",
    ),
    SystemQuoteSeed(
        contentTr = "Her insan sonsuz bir sevgi zenginli\u011fine lay\u0131kt\u0131r; ruhunun g\u00fczelli\u011finin s\u0131n\u0131r\u0131 yoktur.",
        contentEn = "Every person is worthy of an infinite wealth of love \u2014 the beauty of his soul knows no limit.",
        source = "Rabindranath Tagore",
        referenceUrl = "https://en.wikiquote.org/wiki/Rabindranath_Tagore",
    ),
    SystemQuoteSeed(
        contentTr = "\u0130nsanlar\u0131n yollar\u0131 burada ayr\u0131l\u0131r: ruh huzuru ve haz pe\u015findeysen inan; hakikatin takip\u00e7isi olmak istiyorsan sorgula.",
        contentEn = "Here the ways of men part: if you wish to strive for peace of soul and pleasure, then believe; if you wish to be a devotee of truth, then inquire.",
        source = "Friedrich Nietzsche",
        referenceUrl = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche",
    ),
    SystemQuoteSeed(
        contentTr = "Olgular\u0131n \u00f6tesinde durup 'yaln\u0131zca olgular vard\u0131r' diyen o pozitivizme kar\u015f\u0131 \u015funu s\u00f6ylerim: Hay\u0131r, tam tersine, olgular yoktur; yaln\u0131zca yorumlar vard\u0131r.",
        contentEn = "Against that positivism which stops before phenomena, saying \\\\\\\"there are only facts,\\\\\\\" I should say: no, it is precisely facts that do not exist, only interpretations.",
        source = "Friedrich Nietzsche",
        referenceUrl = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche",
    ),
    SystemQuoteSeed(
        contentTr = "Art\u0131k ben, her ayr\u0131nt\u0131da bilgelik i\u00e7in ya\u015fayarak var\u0131m; oysa eskiden yaln\u0131zca bilge olanlara tapar ve onlar\u0131 putla\u015ft\u0131r\u0131rd\u0131m.",
        contentEn = "I now myself live, in every detail, striving for wisdom, while I formerly merely worshipped and idolized the wise.",
        source = "Friedrich Nietzsche",
        referenceUrl = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche",
    ),
    SystemQuoteSeed(
        contentTr = "\u00dcslup, insan\u0131n bir fikre yaln\u0131zca inand\u0131\u011f\u0131n\u0131 de\u011fil, onu hissetti\u011fini de kan\u0131tlamal\u0131d\u0131r.",
        contentEn = "Style ought to prove that one believes in an idea; not only that one thinks it but also feels it.",
        source = "Friedrich Nietzsche",
        referenceUrl = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche",
    ),
    SystemQuoteSeed(
        contentTr = "Yazg\u0131 olmadan \u00f6zg\u00fcr irade, madde olmadan ruh ya da k\u00f6t\u00fcl\u00fck olmadan iyilik kadar d\u00fc\u015f\u00fcn\u00fclemez.",
        contentEn = "Free will without fate is no more conceivable than spirit without matter, good without evil.",
        source = "Friedrich Nietzsche",
        referenceUrl = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche",
    ),
    SystemQuoteSeed(
        contentTr = "Ger\u00e7ekten s\u00f6yleyebilir miyim? B\u00fct\u00fcn hakikatler benim i\u00e7in kanl\u0131 hakikatlerdir \u2014 \u00f6nceki yaz\u0131lar\u0131ma bak\u0131n.",
        contentEn = "May I really say it! All truths are bloody truths to me\u2014take a look at my previous writings.",
        source = "Friedrich Nietzsche",
        referenceUrl = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche",
    ),
    SystemQuoteSeed(
        contentTr = "Do\u011faya egemen olma d\u00fc\u015f\u00fcncesi, 20. y\u00fczy\u0131l\u0131n saplant\u0131l\u0131 fikridir.",
        contentEn = "Mastery over nature, the Id\u00e9e fixe of the 20th century, is Brahmanism, Indo-German.",
        source = "Friedrich Nietzsche",
        referenceUrl = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche",
    ),
    SystemQuoteSeed(
        contentTr = "Sanat\u00e7\u0131 \u2014 sanat\u0131, sanat ara\u00e7lar\u0131yla harekete zorlayan ki\u015fi olarak \u2014 ayn\u0131 anda sanat\u0131n etkinli\u011fini pasif\u00e7e i\u00e7ine alan bir ara\u00e7 olamaz.",
        contentEn = "The artist \u2014 as the one who compels motion through art media toward art \u2014 cannot be simultaneously the absorptive instrument of art's own activity.",
        source = "Friedrich Nietzsche",
        referenceUrl = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche",
    ),
    SystemQuoteSeed(
        contentTr = "O zamanlar o teslimiyet\u00e7ili\u011fe ne kadar da uzakt\u0131m!",
        contentEn = "How far I was then from all that resignationism!",
        source = "Friedrich Nietzsche",
        referenceUrl = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche",
    ),
    SystemQuoteSeed(
        contentTr = "Ba\u015fkalar\u0131na benzemek i\u00e7in kendimizin d\u00f6rtte \u00fc\u00e7\u00fcn\u00fc feda ederiz.",
        contentEn = "We forfeit three-fourths of ourselves in order to be like other people.",
        source = "Arthur Schopenhauer",
        referenceUrl = "https://en.wikiquote.org/wiki/Arthur_Schopenhauer",
    ),
    SystemQuoteSeed(
        contentTr = "D\u00fcnyada ger\u00e7ekten insan\u0131n mal\u0131 denebilecek bir \u015fey varsa, o da zihinsel eme\u011finin \u00fcr\u00fcn\u00fcd\u00fcr.",
        contentEn = "If there is anything in the world that can really be called a man's property, it is surely that which is the result of his mental activity.",
        source = "Arthur Schopenhauer",
        referenceUrl = "https://en.wikiquote.org/wiki/Arthur_Schopenhauer",
    ),
    SystemQuoteSeed(
        contentTr = "N\u00fckte, birbirinden \u00e7ok farkl\u0131 iki ger\u00e7ek nesneyi tek bir kavram alt\u0131nda toplad\u0131\u011f\u0131 gibi, cinas da iki farkl\u0131 kavram\u0131 rastlant\u0131n\u0131n yard\u0131m\u0131yla tek bir s\u00f6zc\u00fck alt\u0131nda toplar.",
        contentEn = "Just as the witticism brings two very different real objects under one concept, the pun brings two different concepts, by the assistance of accident, under one word.",
        source = "Arthur Schopenhauer",
        referenceUrl = "https://en.wikiquote.org/wiki/Arthur_Schopenhauer",
    ),
    SystemQuoteSeed(
        contentTr = "M\u00fczi\u011fin etkisi, \u00f6teki sanatlar\u0131n etkisinden \u00e7ok daha g\u00fc\u00e7l\u00fc ve derindir; \u00e7\u00fcnk\u00fc \u00f6tekiler yaln\u0131zca g\u00f6lgeden, m\u00fczik ise \u00f6zden s\u00f6z eder.",
        contentEn = "The effect of music is so very much more powerful and penetrating than is that of the other arts, for these others speak only of the shadow, but music of the essence.",
        source = "Arthur Schopenhauer",
        referenceUrl = "https://en.wikiquote.org/wiki/Arthur_Schopenhauer",
    ),
    SystemQuoteSeed(
        contentTr = "\u0130\u00e7inde bulundu\u011fumuz ve i\u00e7imizde ta\u015f\u0131d\u0131\u011f\u0131m\u0131z bu bilinebilir ger\u00e7ek d\u00fcnya, d\u00fc\u015f\u00fcncemizin hem malzemesi hem de s\u0131n\u0131r\u0131 olarak kal\u0131r.",
        contentEn = "This actual world of what is knowable, in which we are and which is in us, remains both the material and the limit of our consideration.",
        source = "Arthur Schopenhauer",
        referenceUrl = "https://en.wikiquote.org/wiki/Arthur_Schopenhauer",
    ),
    SystemQuoteSeed(
        contentTr = "Yetenek, ba\u015fkalar\u0131n\u0131n vuramayaca\u011f\u0131 hedefi vurur; deha ise ba\u015fkalar\u0131n\u0131n g\u00f6remedi\u011fi hedefi vurur.",
        contentEn = "Talent hits a target no one else can hit; genius hits a target no one else can see.",
        source = "Arthur Schopenhauer",
        referenceUrl = "https://en.wikiquote.org/wiki/Arthur_Schopenhauer",
    ),
    SystemQuoteSeed(
        contentTr = "Bedenim ve istemim birdir.",
        contentEn = "My body and my will are one.",
        source = "Arthur Schopenhauer",
        referenceUrl = "https://en.wikiquote.org/wiki/Arthur_Schopenhauer",
    ),
    SystemQuoteSeed(
        contentTr = "Hayat, masraf\u0131n\u0131 kar\u015f\u0131lamayan bir i\u015ftir.",
        contentEn = "Life is a business that does not cover the costs.",
        source = "Arthur Schopenhauer",
        referenceUrl = "https://en.wikiquote.org/wiki/Arthur_Schopenhauer",
    ),
    SystemQuoteSeed(
        contentTr = "Bir ki\u015fi aptalsa, bunu elinden gelmedi\u011fi i\u00e7in mazur g\u00f6r\u00fcr\u00fcz; ama ayn\u0131 \u015fekilde k\u00f6t\u00fc birini mazur g\u00f6stermeye kalksak bize g\u00fclerler.",
        contentEn = "If a person is stupid, we excuse him by saying that he cannot help it; but if we attempted to excuse in precisely the same way the person who is bad, we should be laughed at.",
        source = "Arthur Schopenhauer",
        referenceUrl = "https://en.wikiquote.org/wiki/Arthur_Schopenhauer",
    ),
)

